import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

import { logger } from '@/lib/logger';
export async function POST() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Non autorisé en production' }, { status: 403 });
  }

  try {
    // Clean existing seeded data first
    await prisma.roomType.deleteMany({});
    await prisma.hotel.deleteMany({});
    await prisma.restaurant.deleteMany({});
    await prisma.attraction.deleteMany({});
    await prisma.establishmentReview.deleteMany({});
    await prisma.establishmentClaim.deleteMany({});
    await prisma.establishment.deleteMany({});

    // =============================================
    // RESTAURANTS
    // =============================================
    const restaurants = [
      {
        name: 'La Varangue',
        slug: 'la-varangue-antananarivo',
        description: "Restaurant gastronomique emblématique d'Antananarivo, La Varangue propose une cuisine franco-malgache raffinée dans un cadre colonial magnifique. Situé dans la haute ville, il offre une vue imprenable sur la capitale. Les plats mettent en valeur les produits locaux avec une touche française : foie gras au poivre sauvage de Madagascar, zébu grillé aux épices, langouste flambée au rhum arrangé. La carte des vins est exceptionnelle avec des sélections françaises et sud-africaines.",
        shortDescription: 'Cuisine franco-malgache raffinée dans un cadre colonial avec vue sur Tana',
        address: '17 Rue Rainitovo, Haute Ville',
        city: 'Antananarivo',
        district: 'Haute Ville',
        region: 'Analamanga',
        latitude: -18.9137,
        longitude: 47.5261,
        phone: '+261 20 22 275 07',
        email: 'contact@lavarangue.com',
        coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
          'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        ]),
        rating: 4.6,
        reviewCount: 187,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'La Varangue - Restaurant Gastronomique Antananarivo',
        metaDescription: 'Restaurant gastronomique franco-malgache au cœur de la haute ville de Tana. Cuisine raffinée, cadre colonial, vue panoramique.',
        dataSource: 'manual',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['malgache', 'français', 'gastronomique']),
          priceRange: 'UPSCALE' as const,
          openingHours: JSON.stringify({
            lundi: { open: '12:00', close: '14:30' },
            mardi: { open: '12:00', close: '14:30' },
            mercredi: { open: '12:00', close: '14:30' },
            jeudi: { open: '12:00', close: '14:30' },
            vendredi: { open: '12:00', close: '22:00' },
            samedi: { open: '12:00', close: '22:00' },
          }),
          hasReservation: true,
          hasWifi: true,
          hasParking: true,
          hasGenerator: true,
          specialties: JSON.stringify(['Foie gras au poivre sauvage', 'Zébu grillé', 'Langouste flambée']),
          avgMainCourse: 75000,
          avgBeer: 12000,
        },
      },
      {
        name: 'Sakamanga',
        slug: 'sakamanga-antananarivo',
        description: "Institution incontournable d'Antananarivo, le Sakamanga est bien plus qu'un restaurant. C'est un hôtel-restaurant-bar qui incarne l'esprit bohème de Madagascar. La décoration mêle artisanat malgache et touches modernes. La cuisine propose un excellent rapport qualité-prix avec des plats malgaches traditionnels et internationaux. Le romazava (bouillon de brèdes au zébu), le ravitoto (feuilles de manioc pilées au porc) et les brochettes de zébu sont des incontournables.",
        shortDescription: 'Hôtel-restaurant-bar mythique de Tana, cuisine malgache et internationale',
        address: 'Rue Andrianary Ratianarivo, Isoraka',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9100,
        longitude: 47.5235,
        phone: '+261 20 22 358 09',
        website: 'https://www.sakamanga.com',
        email: 'info@sakamanga.com',
        coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
          'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
        ]),
        rating: 4.3,
        reviewCount: 342,
        isFeatured: true,
        metaTitle: 'Sakamanga - Restaurant & Hôtel Antananarivo',
        metaDescription: 'Le Sakamanga, institution mythique d\'Antananarivo. Restaurant, bar et hôtel au cœur de Tana. Cuisine malgache authentique.',
        dataSource: 'manual',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['malgache', 'français', 'international']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({
            lundi: { open: '06:30', close: '23:00' },
            mardi: { open: '06:30', close: '23:00' },
            mercredi: { open: '06:30', close: '23:00' },
            jeudi: { open: '06:30', close: '23:00' },
            vendredi: { open: '06:30', close: '00:00' },
            samedi: { open: '06:30', close: '00:00' },
            dimanche: { open: '06:30', close: '22:00' },
          }),
          hasReservation: true,
          hasWifi: true,
          hasParking: false,
          hasGenerator: true,
          hasTakeaway: true,
          specialties: JSON.stringify(['Romazava', 'Ravitoto', 'Brochettes de zébu', 'Rhum arrangé']),
          avgMainCourse: 25000,
          avgBeer: 8000,
        },
      },
      {
        name: 'Chez Karon',
        slug: 'chez-karon-nosy-be',
        description: "Perché sur une colline avec vue sur la mer, Chez Karon est le restaurant de fruits de mer par excellence de Nosy Be. Les langoustes, crevettes géantes et poissons sont pêchés le jour même par les pêcheurs locaux. Ambiance décontractée pieds dans le sable le midi, plus chic le soir avec bougies et coucher de soleil. Le plateau de fruits de mer pour deux est légendaire. Ne manquez pas le rhum arrangé maison à la vanille de Madagascar.",
        shortDescription: 'Fruits de mer frais face à la mer à Nosy Be, langoustes et coucher de soleil',
        address: 'Ambatoloaka',
        city: 'Nosy Be',
        district: 'Ambatoloaka',
        region: 'Diana',
        latitude: -13.4080,
        longitude: 48.2580,
        phone: '+261 32 07 123 45',
        coverImage: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
          'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
        ]),
        rating: 4.5,
        reviewCount: 156,
        isFeatured: true,
        metaTitle: 'Chez Karon - Fruits de Mer à Nosy Be',
        metaDescription: 'Restaurant de fruits de mer face à la mer à Nosy Be. Langoustes fraîches, crevettes géantes, coucher de soleil.',
        dataSource: 'manual',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['fruits de mer', 'malgache', 'français']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({
            lundi: { open: '11:30', close: '22:00' },
            mardi: { open: '11:30', close: '22:00' },
            mercredi: { open: '11:30', close: '22:00' },
            jeudi: { open: '11:30', close: '22:00' },
            vendredi: { open: '11:30', close: '23:00' },
            samedi: { open: '11:30', close: '23:00' },
            dimanche: { open: '11:30', close: '22:00' },
          }),
          hasReservation: true,
          hasWifi: true,
          hasParking: true,
          specialties: JSON.stringify(['Plateau de fruits de mer', 'Langouste grillée', 'Crevettes géantes', 'Rhum arrangé vanille']),
          avgMainCourse: 40000,
          avgBeer: 8000,
        },
      },
      {
        name: 'Mamy Gargote',
        slug: 'mamy-gargote-antsirabe',
        description: "La gargote de Mamy est une adresse que se partagent les locaux d'Antsirabe. Ici, pas de chichis : on mange une cuisine malgache authentique et copieuse à prix tout doux. Le vary amin'anana (riz aux brèdes), le hen'omby ritra (zébu sauté) et le ravitoto sont préparés avec amour chaque matin. L'ambiance est conviviale, on mange sur de grandes tables communes. C'est l'expérience culinaire malgache la plus authentique que vous trouverez.",
        shortDescription: 'Gargote malgache authentique à Antsirabe, cuisine maison copieuse et pas chère',
        address: 'Rue du Commerce, Centre-ville',
        city: 'Antsirabe',
        district: 'Centre-ville',
        region: 'Vakinankaratra',
        latitude: -19.8659,
        longitude: 47.0333,
        phone: '+261 34 12 345 67',
        coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        rating: 4.2,
        reviewCount: 89,
        metaTitle: 'Mamy Gargote - Cuisine Malgache Antsirabe',
        metaDescription: 'Gargote malgache authentique à Antsirabe. Romazava, ravitoto, vary amin\'anana. Prix locaux, ambiance conviviale.',
        dataSource: 'manual',
        restaurant: {
          category: 'GARGOTE' as const,
          cuisineTypes: JSON.stringify(['malgache']),
          priceRange: 'BUDGET' as const,
          openingHours: JSON.stringify({
            lundi: { open: '06:00', close: '15:00' },
            mardi: { open: '06:00', close: '15:00' },
            mercredi: { open: '06:00', close: '15:00' },
            jeudi: { open: '06:00', close: '15:00' },
            vendredi: { open: '06:00', close: '15:00' },
            samedi: { open: '06:00', close: '14:00' },
          }),
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: false,
          hasParking: false,
          specialties: JSON.stringify(["Vary amin'anana", "Hen'omby ritra", 'Ravitoto', 'Romazava']),
          avgMainCourse: 5000,
          avgBeer: 3000,
        },
      },
      {
        name: 'Le Glacier',
        slug: 'le-glacier-antananarivo',
        description: "Café-restaurant branché du quartier d'Analakely, Le Glacier est le rendez-vous des jeunes Tananariviens. Connu pour ses glaces artisanales aux parfums malgaches (vanille de Madagascar, litchi, baobab), il propose aussi une carte de snacks, salades et plats légers. L'espace est moderne avec WiFi rapide, idéal pour travailler ou se retrouver entre amis. Les jus de fruits frais sont pressés à la commande.",
        shortDescription: 'Café branché à Analakely, glaces artisanales et jus frais',
        address: 'Avenue de l\'Indépendance, Analakely',
        city: 'Antananarivo',
        district: 'Analakely',
        region: 'Analamanga',
        latitude: -18.9075,
        longitude: 47.5236,
        phone: '+261 20 22 234 56',
        coverImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
        rating: 4.1,
        reviewCount: 213,
        metaTitle: 'Le Glacier - Café & Glaces Artisanales Antananarivo',
        metaDescription: 'Café branché à Analakely, Tana. Glaces artisanales vanille Madagascar, jus frais, WiFi rapide.',
        dataSource: 'manual',
        restaurant: {
          category: 'CAFE' as const,
          cuisineTypes: JSON.stringify(['café', 'snacks', 'glaces']),
          priceRange: 'BUDGET' as const,
          openingHours: JSON.stringify({
            lundi: { open: '07:00', close: '21:00' },
            mardi: { open: '07:00', close: '21:00' },
            mercredi: { open: '07:00', close: '21:00' },
            jeudi: { open: '07:00', close: '21:00' },
            vendredi: { open: '07:00', close: '22:00' },
            samedi: { open: '08:00', close: '22:00' },
            dimanche: { open: '08:00', close: '20:00' },
          }),
          hasTakeaway: true,
          hasWifi: true,
          hasGenerator: true,
          specialties: JSON.stringify(['Glace vanille Madagascar', 'Jus de litchi frais', 'Glace baobab', 'Café torréfié local']),
          avgMainCourse: 12000,
          avgBeer: 6000,
        },
      },
      {
        name: 'Ô Bord du Lac',
        slug: 'o-bord-du-lac-antsirabe',
        description: "Situé au bord du lac Ranomafana à Antsirabe, ce lounge-bar offre une ambiance chill avec vue sur l'eau. La carte mélange tapas fusion, cocktails créatifs et plats malgaches revisités. Le week-end, des DJ sets animent les soirées. L'endroit parfait pour un apéro au coucher du soleil. Le brunch du dimanche avec ses crêpes au miel de litchi est très prisé.",
        shortDescription: 'Lounge-bar au bord du lac à Antsirabe, cocktails et tapas fusion',
        address: 'Bord du Lac Ranomafana',
        city: 'Antsirabe',
        region: 'Vakinankaratra',
        latitude: -19.8712,
        longitude: 47.0315,
        phone: '+261 33 45 678 90',
        coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
        rating: 4.0,
        reviewCount: 78,
        metaTitle: 'Ô Bord du Lac - Lounge Bar Antsirabe',
        metaDescription: 'Lounge-bar au bord du lac Ranomafana, Antsirabe. Cocktails, tapas fusion, DJ sets le week-end.',
        dataSource: 'manual',
        restaurant: {
          category: 'LOUNGE' as const,
          cuisineTypes: JSON.stringify(['fusion', 'tapas', 'cocktails']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({
            mardi: { open: '16:00', close: '00:00' },
            mercredi: { open: '16:00', close: '00:00' },
            jeudi: { open: '16:00', close: '00:00' },
            vendredi: { open: '16:00', close: '02:00' },
            samedi: { open: '11:00', close: '02:00' },
            dimanche: { open: '11:00', close: '22:00' },
          }),
          hasReservation: true,
          hasWifi: true,
          hasParking: true,
          specialties: JSON.stringify(['Cocktail Baobab Sour', 'Tapas zébu fumé', 'Brunch dimanche']),
          avgMainCourse: 30000,
          avgBeer: 10000,
        },
      },
      {
        name: 'Mofo Gasy Stand Rasoa',
        slug: 'mofo-gasy-stand-rasoa-antananarivo',
        description: "Le stand de Rasoa est une institution du street food tananarivien. Chaque matin dès 5h, elle prépare les meilleurs mofo gasy (beignets de riz) de la ville, croustillants à l'extérieur et moelleux à l'intérieur. Accompagnés de café torréfié local et de sambos (samossas malgaches), c'est le petit-déjeuner typique des Tananariviens. Le koba (gâteau de riz et cacahuètes enveloppé dans des feuilles de bananier) est à ne pas manquer.",
        shortDescription: 'Street food malgache, les meilleurs mofo gasy de Tana depuis 20 ans',
        address: 'Marché Analakely',
        city: 'Antananarivo',
        district: 'Analakely',
        region: 'Analamanga',
        latitude: -18.9078,
        longitude: 47.5240,
        phone: '+261 34 56 789 01',
        coverImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        rating: 4.4,
        reviewCount: 267,
        isFeatured: true,
        metaTitle: 'Mofo Gasy Stand Rasoa - Street Food Antananarivo',
        metaDescription: 'Les meilleurs mofo gasy de Tana ! Beignets de riz, sambos, koba. Street food malgache authentique au marché Analakely.',
        dataSource: 'manual',
        restaurant: {
          category: 'STREET_FOOD' as const,
          cuisineTypes: JSON.stringify(['malgache', 'street food']),
          priceRange: 'BUDGET' as const,
          openingHours: JSON.stringify({
            lundi: { open: '05:00', close: '11:00' },
            mardi: { open: '05:00', close: '11:00' },
            mercredi: { open: '05:00', close: '11:00' },
            jeudi: { open: '05:00', close: '11:00' },
            vendredi: { open: '05:00', close: '11:00' },
            samedi: { open: '05:00', close: '12:00' },
            dimanche: { open: '06:00', close: '11:00' },
          }),
          hasTakeaway: true,
          specialties: JSON.stringify(['Mofo gasy', 'Sambos', 'Koba', 'Café local']),
          avgMainCourse: 2000,
          avgBeer: 2000,
        },
      },
      {
        name: 'Pizza Tana Express',
        slug: 'pizza-tana-express-antananarivo',
        description: "Fast-food à la malgache proposant pizzas, burgers et plats rapides avec des ingrédients locaux. La pizza Zébu BBQ et le burger au fromage de vache malgache sont les best-sellers. Service rapide, livraison disponible dans tout Tana. Idéal pour un repas sur le pouce avec la famille.",
        shortDescription: 'Fast-food local, pizzas et burgers avec ingrédients malgaches, livraison Tana',
        address: '67 Ha, Antananarivo',
        city: 'Antananarivo',
        district: '67 Ha',
        region: 'Analamanga',
        latitude: -18.9150,
        longitude: 47.5200,
        phone: '+261 32 11 222 33',
        coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
        rating: 3.9,
        reviewCount: 145,
        metaTitle: 'Pizza Tana Express - Fast Food Antananarivo',
        metaDescription: 'Pizzas et burgers avec ingrédients malgaches. Livraison rapide dans tout Tana.',
        dataSource: 'manual',
        restaurant: {
          category: 'FAST_FOOD' as const,
          cuisineTypes: JSON.stringify(['fast food', 'pizza', 'burger']),
          priceRange: 'BUDGET' as const,
          openingHours: JSON.stringify({
            lundi: { open: '10:00', close: '22:00' },
            mardi: { open: '10:00', close: '22:00' },
            mercredi: { open: '10:00', close: '22:00' },
            jeudi: { open: '10:00', close: '22:00' },
            vendredi: { open: '10:00', close: '23:00' },
            samedi: { open: '10:00', close: '23:00' },
            dimanche: { open: '11:00', close: '22:00' },
          }),
          hasDelivery: true,
          hasTakeaway: true,
          hasWifi: true,
          specialties: JSON.stringify(['Pizza Zébu BBQ', 'Burger fromage malgache', 'Nems au zébu']),
          avgMainCourse: 15000,
          avgBeer: 5000,
        },
      },
    ];

    // =============================================
    // HOTELS
    // =============================================
    const hotels = [
      {
        name: 'Carlton Madagascar',
        slug: 'carlton-madagascar-antananarivo',
        description: "Le Carlton Madagascar est l'hôtel de référence de la capitale. Situé en plein cœur d'Antananarivo avec vue sur le lac Anosy, cet hôtel 5 étoiles offre un service impeccable, des chambres luxueuses et plusieurs restaurants dont le célèbre Le Fangalana. Piscine, spa, salle de fitness et centre de conférence complètent les installations. L'architecture Art Déco rappelle l'élégance coloniale tandis que la décoration intérieure met en valeur l'artisanat malgache.",
        shortDescription: 'Hôtel 5 étoiles de référence à Tana, vue lac Anosy, spa et gastronomie',
        address: 'Rue Pierre Stibbe, Anosy',
        city: 'Antananarivo',
        district: 'Anosy',
        region: 'Analamanga',
        latitude: -18.9200,
        longitude: 47.5220,
        phone: '+261 20 22 260 60',
        email: 'reservation@carlton-madagascar.com',
        website: 'https://www.carlton-madagascar.com',
        coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
          'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        ]),
        rating: 4.7,
        reviewCount: 423,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'Carlton Madagascar - Hôtel 5 Étoiles Antananarivo',
        metaDescription: 'Hôtel 5 étoiles au cœur de Tana. Vue lac Anosy, spa, piscine, restaurants gastronomiques. Le luxe à la malgache.',
        dataSource: 'manual',
        hotel: {
          starRating: 5,
          hotelType: 'hotel de luxe',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'gym', 'bar', 'room_service', 'laundry']),
          checkInTime: '14:00',
          checkOutTime: '12:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar']) },
            { name: 'Chambre Supérieure', capacity: 2, pricePerNight: 400000, priceWeekend: 450000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_lac']) },
            { name: 'Suite Royale', capacity: 3, pricePerNight: 800000, priceWeekend: 900000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_lac', 'jacuzzi', 'salon']) },
          ],
        },
      },
      {
        name: 'Anjajavy le Lodge',
        slug: 'anjajavy-le-lodge',
        description: "Niché dans une réserve naturelle privée de 450 hectares sur la côte nord-ouest de Madagascar, Anjajavy le Lodge est l'un des écolodges les plus exclusifs de l'île. Accessible uniquement par avion, les 24 villas en bois de palissandre s'intègrent parfaitement dans la forêt tropicale. Plages désertes de sable blanc, forêt de tsingy, lémuriens en liberté, plongée dans des eaux cristallines. Le restaurant propose une cuisine gastronomique avec les produits de la pêche du jour et du potager bio.",
        shortDescription: 'Écolodge exclusif dans une réserve privée, plage, lémuriens et gastronomie',
        address: 'Presqu\'île d\'Anjajavy',
        city: 'Anjajavy',
        region: 'Sofia',
        latitude: -15.0167,
        longitude: 47.2333,
        phone: '+261 20 22 397 60',
        email: 'booking@anjajavy.com',
        website: 'https://www.anjajavy.com',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
          'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
        ]),
        rating: 4.9,
        reviewCount: 98,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'Anjajavy le Lodge - Écolodge de Luxe Madagascar',
        metaDescription: 'Écolodge exclusif dans une réserve privée. Villas en palissandre, plage privée, lémuriens, gastronomie. Madagascar authentique.',
        dataSource: 'manual',
        hotel: {
          starRating: 5,
          hotelType: 'ecolodge',
          amenities: JSON.stringify(['wifi', 'generator', 'restaurant', 'spa', 'bar', 'plage_privee', 'excursions', 'plongee']),
          checkInTime: '12:00',
          checkOutTime: '10:00',
          roomTypes: [
            { name: 'Villa Rosewood', capacity: 2, pricePerNight: 1200000, amenities: JSON.stringify(['terrasse', 'vue_mer', 'douche_exterieure']) },
            { name: 'Villa Familiale', capacity: 4, pricePerNight: 1800000, amenities: JSON.stringify(['terrasse', 'vue_mer', 'salon', 'deux_chambres']) },
          ],
        },
      },
      {
        name: 'Hôtel Colbert',
        slug: 'hotel-colbert-antananarivo',
        description: "Hôtel historique et institution de Tana depuis des décennies, le Colbert propose un confort 4 étoiles dans le quartier d'Antaninarenina. Récemment rénové, il conserve son cachet tout en offrant des équipements modernes. Plusieurs restaurants, dont une brasserie française et un restaurant malgache. Position centrale idéale pour explorer la capitale.",
        shortDescription: 'Hôtel historique 4 étoiles au centre de Tana, brasserie et confort moderne',
        address: 'Rue Prince Ratsimamanga, Antaninarenina',
        city: 'Antananarivo',
        district: 'Antaninarenina',
        region: 'Analamanga',
        latitude: -18.9115,
        longitude: 47.5255,
        phone: '+261 20 22 202 02',
        email: 'info@hotelcolbert.com',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
          'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
        ]),
        rating: 4.2,
        reviewCount: 312,
        isFeatured: true,
        metaTitle: 'Hôtel Colbert - Hôtel 4 Étoiles Antananarivo',
        metaDescription: 'Hôtel historique 4 étoiles au centre de Tana. Brasserie française, confort moderne, position idéale.',
        dataSource: 'manual',
        hotel: {
          starRating: 4,
          hotelType: 'hotel',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'restaurant', 'ac', 'tv', 'bar', 'room_service', 'laundry']),
          checkInTime: '14:00',
          checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 150000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Chambre Deluxe', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_ville']) },
          ],
        },
      },
      {
        name: 'Chez Maggie',
        slug: 'chez-maggie-nosy-be',
        description: "Charmant boutique-hôtel à Ambatoloaka, Nosy Be. Chez Maggie propose des bungalows colorés dans un jardin tropical luxuriant à deux pas de la plage. Ambiance familiale, accueil chaleureux et petit-déjeuner copieux avec fruits frais. Le restaurant sert d'excellents fruits de mer. Parfait pour les voyageurs cherchant authenticité et confort sans se ruiner.",
        shortDescription: 'Boutique-hôtel charmant à Nosy Be, bungalows tropicaux près de la plage',
        address: 'Ambatoloaka, Nosy Be',
        city: 'Nosy Be',
        district: 'Ambatoloaka',
        region: 'Diana',
        latitude: -13.4065,
        longitude: 48.2575,
        phone: '+261 32 04 567 89',
        coverImage: 'https://images.unsplash.com/photo-1499793983394-12042d5ee400?w=800',
        rating: 4.4,
        reviewCount: 189,
        metaTitle: 'Chez Maggie - Boutique Hôtel Nosy Be',
        metaDescription: 'Boutique-hôtel à Nosy Be. Bungalows tropicaux, jardin luxuriant, plage à 2 min. Ambiance familiale.',
        dataSource: 'manual',
        hotel: {
          starRating: 3,
          hotelType: 'boutique',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'restaurant', 'bar', 'plage']),
          checkInTime: '13:00',
          checkOutTime: '11:00',
          roomTypes: [
            { name: 'Bungalow Standard', capacity: 2, pricePerNight: 80000, amenities: JSON.stringify(['ventilateur', 'moustiquaire']) },
            { name: 'Bungalow Supérieur', capacity: 2, pricePerNight: 120000, amenities: JSON.stringify(['ac', 'terrasse', 'vue_jardin']) },
            { name: 'Bungalow Familial', capacity: 4, pricePerNight: 160000, amenities: JSON.stringify(['ac', 'terrasse', 'deux_lits']) },
          ],
        },
      },
    ];

    // =============================================
    // ATTRACTIONS
    // =============================================
    const attractions = [
      {
        name: 'Allée des Baobabs',
        slug: 'allee-des-baobabs-morondava',
        description: "L'Allée des Baobabs est sans doute le site le plus photographié de Madagascar. Cette rangée spectaculaire de baobabs Grandidier (Adansonia grandidieri) borde une piste de terre rouge entre Morondava et Belon'i Tsiribihina. Ces arbres majestueux, certains vieux de plus de 800 ans, atteignent 30 mètres de haut. Le coucher de soleil y est absolument magique, transformant les silhouettes des baobabs en un spectacle inoubliable. Classé monument naturel, le site est un symbole de Madagascar.",
        shortDescription: 'Rangée spectaculaire de baobabs millénaires, coucher de soleil magique',
        address: 'Route de Belo sur Tsiribihina',
        city: 'Morondava',
        region: 'Menabe',
        latitude: -20.2508,
        longitude: 44.4183,
        coverImage: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=800',
          'https://images.unsplash.com/photo-1590418606746-018840f9cd0f?w=800',
        ]),
        rating: 4.8,
        reviewCount: 534,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'Allée des Baobabs - Monument Naturel Morondava',
        metaDescription: 'L\'Allée des Baobabs, site emblématique de Madagascar. Baobabs millénaires, coucher de soleil magique. Incontournable à Morondava.',
        dataSource: 'manual',
        attraction: {
          attractionType: 'viewpoint',
          isFree: false,
          entryFeeForeign: 10000,
          entryFeeLocal: 2000,
          visitDuration: '1-2 heures',
          bestTimeToVisit: 'Coucher de soleil (17h-18h)',
          bestSeason: 'avril-novembre',
          hasGuide: true,
          hasParking: true,
          highlights: JSON.stringify(['Baobabs Grandidieri de 800 ans', 'Coucher de soleil spectaculaire', 'Piste de terre rouge', 'Photo emblématique de Madagascar']),
        },
      },
      {
        name: 'Parc National de l\'Isalo',
        slug: 'parc-national-isalo',
        description: "Le Parc National de l'Isalo est un massif de grès ruiniforme surnommé le \"Colorado malgache\". Ses canyons profonds, ses piscines naturelles turquoise, ses grottes et ses formations rocheuses sculptées par l'érosion en font un paradis pour les randonneurs. La Piscine Naturelle, la Fenêtre de l'Isalo (idéale au coucher du soleil) et le Canyon des Makis sont les points forts. La flore endémique inclut l'Aloès de l'Isalo et le palmier de l'Isalo. Lémuriens Maki catta et Sifaka visibles.",
        shortDescription: 'Le "Colorado malgache", canyons, piscines naturelles et lémuriens',
        address: 'Route Nationale 7, Ranohira',
        city: 'Ranohira',
        region: 'Ihorombe',
        latitude: -22.5333,
        longitude: 45.3667,
        phone: '+261 20 22 415 54',
        coverImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
          'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
        ]),
        rating: 4.7,
        reviewCount: 412,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'Parc National de l\'Isalo - Randonnée et Nature Madagascar',
        metaDescription: 'Parc National de l\'Isalo, le Colorado malgache. Canyons, piscines naturelles turquoise, lémuriens. Randonnées inoubliables.',
        dataSource: 'manual',
        attraction: {
          attractionType: 'park',
          isFree: false,
          entryFeeForeign: 65000,
          entryFeeLocal: 10000,
          visitDuration: 'Journée entière',
          bestTimeToVisit: 'Tôt le matin pour éviter la chaleur',
          bestSeason: 'avril-octobre',
          isAccessible: false,
          hasGuide: true,
          hasParking: true,
          hasRestaurant: true,
          highlights: JSON.stringify(['Piscine Naturelle turquoise', 'Fenêtre de l\'Isalo au coucher du soleil', 'Canyon des Makis', 'Lémuriens Maki catta', 'Formations rocheuses uniques']),
        },
      },
      {
        name: 'Tsingy de Bemaraha',
        slug: 'tsingy-de-bemaraha',
        description: "Classé au patrimoine mondial de l'UNESCO, le Tsingy de Bemaraha est un paysage unique au monde. Ces immenses aiguilles calcaires acérées forment un labyrinthe minéral spectaculaire. Le parcours via ferrata avec ponts suspendus et échelles offre une aventure inoubliable au-dessus du vide. Le site abrite 11 espèces de lémuriens, des oiseaux rares et une flore endémique. Les Grands Tsingy (plus spectaculaires) et les Petits Tsingy (plus accessibles) offrent deux expériences complémentaires.",
        shortDescription: 'Patrimoine UNESCO, cathédrale minérale et via ferrata au-dessus du vide',
        address: 'Parc National Tsingy de Bemaraha',
        city: 'Bekopaka',
        region: 'Melaky',
        latitude: -19.0833,
        longitude: 44.8167,
        coverImage: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=800',
        ]),
        rating: 4.9,
        reviewCount: 267,
        isFeatured: true,
        isPremium: true,
        metaTitle: 'Tsingy de Bemaraha - Patrimoine UNESCO Madagascar',
        metaDescription: 'Tsingy de Bemaraha, patrimoine mondial UNESCO. Aiguilles calcaires, via ferrata, lémuriens. Aventure unique à Madagascar.',
        dataSource: 'manual',
        attraction: {
          attractionType: 'reserve',
          isFree: false,
          entryFeeForeign: 65000,
          entryFeeLocal: 10000,
          visitDuration: 'Journée entière',
          bestTimeToVisit: 'Saison sèche uniquement (route impraticable en saison des pluies)',
          bestSeason: 'mai-novembre',
          isAccessible: false,
          hasGuide: true,
          hasParking: true,
          highlights: JSON.stringify(['Patrimoine mondial UNESCO', 'Via ferrata et ponts suspendus', 'Grands Tsingy et Petits Tsingy', '11 espèces de lémuriens', 'Formations calcaires uniques au monde']),
        },
      },
      {
        name: 'Nosy Iranja',
        slug: 'nosy-iranja',
        description: "Nosy Iranja, surnommée \"l'île aux tortues\", est composée de deux îlots reliés par un banc de sable blanc immaculé de 2 km qui n'apparaît qu'à marée basse. Les eaux turquoise abritent tortues marines, raies et une vie sous-marine extraordinaire. L'île est un site de ponte pour les tortues vertes et imbriquées. Le snorkeling y est exceptionnel. Accessible en bateau depuis Nosy Be (environ 1h30), c'est une excursion à la journée inoubliable.",
        shortDescription: 'Île paradisiaque avec banc de sable, tortues marines et eaux turquoise',
        address: 'Archipel de Nosy Be',
        city: 'Nosy Be',
        region: 'Diana',
        latitude: -13.7833,
        longitude: 47.8500,
        coverImage: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
        images: JSON.stringify([
          'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
          'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
        ]),
        rating: 4.8,
        reviewCount: 345,
        isFeatured: true,
        metaTitle: 'Nosy Iranja - Île Paradisiaque Madagascar',
        metaDescription: 'Nosy Iranja, île aux tortues. Banc de sable blanc, eaux turquoise, tortues marines. Excursion depuis Nosy Be.',
        dataSource: 'manual',
        attraction: {
          attractionType: 'beach',
          isFree: false,
          entryFeeForeign: 25000,
          entryFeeLocal: 5000,
          visitDuration: 'Journée entière',
          bestTimeToVisit: 'Marée basse pour le banc de sable',
          bestSeason: 'avril-décembre',
          hasGuide: true,
          hasRestaurant: true,
          highlights: JSON.stringify(['Banc de sable de 2 km à marée basse', 'Tortues marines', 'Snorkeling exceptionnel', 'Eaux turquoise cristallines']),
        },
      },
    ];

    // =============================================
    // INSERT ALL DATA
    // =============================================
    let created = { restaurants: 0, hotels: 0, attractions: 0 };

    // Insert restaurants
    for (const r of restaurants) {
      const { restaurant: restData, ...establishmentData } = r;
      await prisma.establishment.create({
        data: {
          type: 'RESTAURANT',
          ...establishmentData,
          restaurant: {
            create: restData,
          },
        },
      });
      created.restaurants++;
    }

    // Insert hotels
    for (const h of hotels) {
      const { hotel: hotelData, ...establishmentData } = h;
      const { roomTypes, ...hotelFields } = hotelData;
      await prisma.establishment.create({
        data: {
          type: 'HOTEL',
          ...establishmentData,
          hotel: {
            create: {
              ...hotelFields,
              roomTypes: {
                create: roomTypes,
              },
            },
          },
        },
      });
      created.hotels++;
    }

    // Insert attractions
    for (const a of attractions) {
      const { attraction: attrData, ...establishmentData } = a;
      await prisma.establishment.create({
        data: {
          type: 'ATTRACTION',
          ...establishmentData,
          attraction: {
            create: attrData,
          },
        },
      });
      created.attractions++;
    }

    return NextResponse.json({
      success: true,
      message: `Seed terminé ! ${created.restaurants} restaurants, ${created.hotels} hôtels, ${created.attractions} attractions créés.`,
      created,
    });
  } catch (error: unknown) {
    logger.error('Seed error:', error);
    const message = error instanceof Error ? error.message : 'Erreur inconnue';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
