import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

import { logger } from '@/lib/logger';
// Seed vérifié - Établissements réels de Madagascar sourcés depuis TripAdvisor, Wanderlog, Booking, PetitFuté
// Tous en statut "pending_review" pour modération admin

export async function POST() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Non autorisé en production' }, { status: 403 });
  }

  try {
    let created = { restaurants: 0, hotels: 0, attractions: 0, skipped: 0 };

    const establishments = [
      // =============================================
      // ANTANANARIVO - RESTAURANTS (vérifiés)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Marais Restaurant',
        slug: 'marais-restaurant-antananarivo',
        description: "Considéré comme le meilleur restaurant de Madagascar et l'un des meilleurs de l'océan Indien. Cuisine française haute gastronomie préparée devant les convives, avec vue panoramique depuis le 5ème étage de l'Immeuble Atrium. Menu dégustation du chef, accords mets-vins exceptionnels.",
        shortDescription: 'Fine dining au 5ème étage, meilleur restaurant de Madagascar',
        address: 'Routes des Hydrocarbures, Immeuble Atrium Ankorondrano, 5è étage',
        city: 'Antananarivo',
        district: 'Ankorondrano',
        region: 'Analamanga',
        latitude: -18.8920,
        longitude: 47.5180,
        phone: '+261 34 50 674 97',
        website: 'https://marais-restaurant.com',
        coverImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        rating: 4.6,
        reviewCount: 91,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293809-d17651597-Reviews-Marais_Restaurant-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fusion'],
          priceRange: 'LUXURY',
          avgMainCourse: 95000,
          avgBeer: 15000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
          openingHours: {
            tuesday: { open: '12:00', close: '14:00' },
            wednesday: { open: '12:00', close: '14:00' },
            thursday: { open: '12:00', close: '14:00' },
            friday: { open: '12:00', close: '14:00' },
            saturday: { open: '12:00', close: '14:00' },
            tuesdayEvening: { open: '19:00', close: '21:30' },
            wednesdayEvening: { open: '19:00', close: '21:30' },
            thursdayEvening: { open: '19:00', close: '21:30' },
            fridayEvening: { open: '19:00', close: '21:30' },
            saturdayEvening: { open: '19:00', close: '21:30' },
          },
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Carnivore',
        slug: 'le-carnivore-antananarivo',
        description: "Restaurant-bar-lounge unique à Antananarivo proposant un concept churrasco brésilien all-you-can-eat. Sélection de viandes exotiques : zébu, crocodile, autruche, sanglier, en plus du bœuf, porc et agneau. Ambiance festive et branchée.",
        shortDescription: 'Churrasco brésilien, viandes exotiques all-you-can-eat',
        address: '66 Rue Ratsimilaho Ambatonakanga, Lalana Ranavalona III',
        city: 'Antananarivo',
        district: 'Ambatonakanga',
        region: 'Analamanga',
        latitude: -18.9100,
        longitude: 47.5270,
        phone: '+261 38 55 125 04',
        coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
        rating: 4.2,
        reviewCount: 324,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293809-d2541126-Reviews-Le_Carnivore-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['brésilien', 'grillades', 'viandes'],
          priceRange: 'UPSCALE',
          avgMainCourse: 55000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Petit Verdot',
        slug: 'le-petit-verdot-antananarivo',
        description: "Fine dining français au cœur de Tana. Spécialités de langoustes et crevettes, carte des vins exceptionnelle. Cadre cosy et intime, idéal pour les occasions spéciales. L'un des restaurants les mieux notés de la capitale.",
        shortDescription: 'Fine dining français, langoustes et carte des vins',
        address: 'Lalana S. Rahamefy',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9130,
        longitude: 47.5290,
        phone: '+261 20 22 392 34',
        coverImage: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
        rating: 4.5,
        reviewCount: 235,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fruits de mer'],
          priceRange: 'UPSCALE',
          avgMainCourse: 65000,
          avgBeer: 12000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Plantation',
        slug: 'la-plantation-antananarivo',
        description: "Restaurant français et international réputé pour sa roue de fromage flambée (les jeudis), son atmosphère sophistiquée et son menu diversifié. Cadre élégant, service attentionné. Une valeur sûre de la gastronomie tananarivienne.",
        shortDescription: 'Restaurant chic, roue de fromage flambée les jeudis',
        address: 'Ivandry',
        city: 'Antananarivo',
        district: 'Ivandry',
        region: 'Analamanga',
        latitude: -18.8950,
        longitude: 47.5350,
        phone: '+261 34 13 416 80',
        coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=800',
        rating: 4.5,
        reviewCount: 248,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'international', 'fromages'],
          priceRange: 'UPSCALE',
          avgMainCourse: 50000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Phare d\'Ivandry',
        slug: 'le-phare-divandry-antananarivo',
        description: "Restaurant-crêperie en pleine nature à Ivandry. Terrasse jardin avec aire de jeux, crêpes et galettes bretonnes, pizzas au feu de bois. Produits du terroir : miel, confitures. Un havre de paix en plein Tana.",
        shortDescription: 'Crêperie-pizzeria en jardin, aire de jeux enfants',
        address: 'Ivandry',
        city: 'Antananarivo',
        district: 'Ivandry',
        region: 'Analamanga',
        latitude: -18.8960,
        longitude: 47.5380,
        phone: '+261 32 42 123 25',
        coverImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
        rating: 4.6,
        reviewCount: 85,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['crêperie', 'pizza', 'français'],
          priceRange: 'MODERATE',
          avgMainCourse: 18000,
          avgBeer: 7000,
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Compagnie des Voyageurs',
        slug: 'la-compagnie-des-voyageurs-antananarivo',
        description: "Restaurant moderne à Ivandry, décor contemporain soigné. Pizzas signature (chèvre-miel), plats internationaux, cocktails créatifs. Personnel attentionné et cadre branché. Un incontournable pour les expats et locaux.",
        shortDescription: 'Restaurant moderne, pizzas signature chèvre-miel',
        address: 'Lot II Ivandry JF Bis',
        city: 'Antananarivo',
        district: 'Ivandry',
        region: 'Analamanga',
        latitude: -18.8945,
        longitude: 47.5365,
        phone: '+261 34 08 130 30',
        coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
        rating: 4.3,
        reviewCount: 66,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['international', 'pizza', 'cocktails'],
          priceRange: 'MODERATE',
          avgMainCourse: 28000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Carré',
        slug: 'le-carre-antananarivo',
        description: "Restaurant fusion légèrement chic à Ambatomena. Menu très varié : plats français, burgers, pizzas, sushis. Décoration moderne et verdoyante. Spécialités : sushis, canard rôti à l'orange, côtes caramélisées, tajine d'agneau.",
        shortDescription: 'Restaurant fusion chic, sushis et cuisine française',
        address: 'Làlana Solombavambahoaka Frantsay 77',
        city: 'Antananarivo',
        district: 'Ambatomena',
        region: 'Analamanga',
        latitude: -18.9120,
        longitude: 47.5250,
        phone: '+261 32 72 299 01',
        coverImage: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
        rating: 3.8,
        reviewCount: 194,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293809-d1214617-Reviews-Le_Carre-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['fusion', 'français', 'sushi', 'pizza'],
          priceRange: 'MODERATE',
          avgMainCourse: 22000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
          openingHours: {
            monday: { open: '11:30', close: '14:30' },
            tuesday: { open: '11:30', close: '14:30' },
            wednesday: { open: '11:30', close: '14:30' },
            thursday: { open: '11:30', close: '14:30' },
            friday: { open: '11:30', close: '14:30' },
            saturday: { open: '11:30', close: '14:30' },
            mondayEvening: { open: '19:00', close: '22:30' },
            tuesdayEvening: { open: '19:00', close: '22:30' },
            wednesdayEvening: { open: '19:00', close: '22:30' },
            thursdayEvening: { open: '19:00', close: '22:30' },
            fridayEvening: { open: '19:00', close: '22:30' },
            saturdayEvening: { open: '19:00', close: '22:30' },
          },
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Buffet du Jardin',
        slug: 'le-buffet-du-jardin-antananarivo',
        description: "Restaurant avec jardin au cœur de Tana, Place de l'Indépendance. Cadre verdoyant charmant, cocktails inventifs, menu international. Brunch le dimanche, idéal pour une pause déjeuner tranquille en centre-ville.",
        shortDescription: 'Restaurant jardin, Place de l\'Indépendance',
        address: "Place de l'Indépendance",
        city: 'Antananarivo',
        district: 'Centre-ville',
        region: 'Analamanga',
        latitude: -18.9080,
        longitude: 47.5230,
        phone: '+261 20 22 338 87',
        coverImage: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
        rating: 3.7,
        reviewCount: 218,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'CAFE',
          cuisineTypes: ['international', 'brunch', 'cocktails'],
          priceRange: 'MODERATE',
          avgMainCourse: 20000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: false,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Restaurant Pizzeria Chez Arnaud',
        slug: 'chez-arnaud-antananarivo',
        description: "Pizzeria italienne authentique à Tana. Pizzas cuites au feu de bois, livraison disponible. Prix raisonnables pour une qualité italienne. Ambiance décontractée, idéal en famille.",
        shortDescription: 'Pizzeria italienne authentique, livraison disponible',
        address: 'Antananarivo',
        city: 'Antananarivo',
        district: null,
        region: 'Analamanga',
        latitude: -18.9100,
        longitude: 47.5260,
        phone: '+261 38 95 632 11',
        coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
        rating: 4.2,
        reviewCount: 32,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://wanderlog.com/list/geoCategory/205440/where-to-eat-best-restaurants-in-antananarivo',
        sourceAttribution: 'Wanderlog',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'pizza'],
          priceRange: 'BUDGET',
          avgMainCourse: 15000,
          avgBeer: 6000,
          hasDelivery: true,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: false,
        },
      },

      // =============================================
      // ANTANANARIVO - HÔTELS (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Lokanga Boutique Hotel',
        slug: 'lokanga-boutique-hotel-antananarivo',
        description: "Hôtel boutique dans un bâtiment franco-malgache historique à Ambohimitsimbina, Haute-Ville. Architecture et design remarquables, vue panoramique sur Tana. Demeure de charme rénovée, ambiance unique et authentique. Paiement en espèces uniquement.",
        shortDescription: 'Boutique hôtel historique, architecture franco-malgache, Haute-Ville',
        address: 'Lot VW 115 Ambohimitsimbina, Haute-Ville',
        city: 'Antananarivo',
        district: 'Haute-Ville',
        region: 'Analamanga',
        latitude: -18.9175,
        longitude: 47.5295,
        phone: '+261 32 03 530 71',
        website: 'http://www.lokanga-hotel.mg',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
        rating: 4.8,
        reviewCount: 156,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293809-d2260947-Reviews-Lokanga_Boutique_Hotel-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'boutique',
          amenities: ['wifi', 'restaurant', 'jardin', 'vue_panoramique', 'terrasse'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 110000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Les 3 Métis',
        slug: 'les-3-metis-antananarivo',
        description: "Demeure historique de 1913 soigneusement rénovée dans le respect de l'architecture malgache. Hôtel de charme avec spa et massages, jardin tropical. Ambiance intime et authentique au cœur d'Antaninandro.",
        shortDescription: 'Demeure historique 1913, spa et architecture malgache',
        address: 'Lot Iva 1 Antaninandro',
        city: 'Antananarivo',
        district: 'Antaninandro',
        region: 'Analamanga',
        latitude: -18.9034,
        longitude: 47.5295,
        phone: '+261 20 22 254 04',
        website: 'https://les-trois-metis.com',
        coverImage: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
        rating: 4.5,
        reviewCount: 289,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293809-d680215-Reviews-Les_Trois_Metis-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'boutique',
          amenities: ['wifi', 'spa', 'restaurant', 'jardin', 'massage', 'terrasse'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 130000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Radisson Blu Antananarivo Waterfront',
        slug: 'radisson-blu-antananarivo',
        description: "Hôtel 5 étoiles international au bord du lac, zone Tana Waterfront. Piscine intérieure, centre fitness, spa, terrasse et jardins luxuriants. Standard international Radisson avec restaurant gastronomique. Le plus moderne de la capitale.",
        shortDescription: 'Hôtel 5 étoiles international, piscine et spa, Tana Waterfront',
        address: 'Zone Tana Waterfront, Ankorondrano',
        city: 'Antananarivo',
        district: 'Ankorondrano',
        region: 'Analamanga',
        latitude: -18.8900,
        longitude: 47.5200,
        phone: '+261 20 22 693 00',
        website: 'https://www.radissonhotels.com/en-us/hotels/radisson-blu-antananarivo-waterfront',
        coverImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        rating: 4.5,
        reviewCount: 387,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293809-d1553285-Reviews-Radisson_Blu_Hotel_Antananarivo_Waterfront-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 5,
          hotelType: 'hotel de luxe',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'gym', 'bar', 'room_service', 'laundry', 'piscine_interieure'],
          checkInTime: '15:00',
          checkOutTime: '12:00',
          lowestPrice: 350000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Relais des Plateaux',
        slug: 'relais-des-plateaux-antananarivo',
        description: "Hôtel 4 étoiles à Ivato, à 15km de l'aéroport international. Spa, piscine, salles de séminaire. Idéal pour escale ou séjour d'affaires. Cadre verdoyant et calme, loin de l'agitation de la capitale.",
        shortDescription: 'Hôtel 4 étoiles avec spa, proche aéroport Ivato',
        address: 'Lot 66 B Antanetibe Ivato',
        city: 'Antananarivo',
        district: 'Ivato',
        region: 'Analamanga',
        latitude: -18.7950,
        longitude: 47.4780,
        phone: '+261 20 22 441 18',
        website: 'https://www.relais-des-plateaux.com',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        rating: 4.2,
        reviewCount: 245,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293809-d1184019-Reviews-Le_Relais_des_Plateaux_Hotel_Spa-Antananarivo_Antananarivo_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 4,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'bar', 'seminaire'],
          checkInTime: '14:00',
          checkOutTime: '12:00',
          lowestPrice: 180000,
        },
      },

      // =============================================
      // NOSY BE - RESTAURANTS & HÔTELS (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Royal Andilana Resort & Spa',
        slug: 'royal-andilana-nosy-be',
        description: "Resort 5 étoiles sur la mythique plage d'Andilana, l'une des plus belles de Nosy Be. 3 piscines, plage privée, spa, 3 restaurants, salle de sport. Bungalows luxueux avec vue mer. Le plus haut standing de l'île.",
        shortDescription: 'Resort 5 étoiles, plage d\'Andilana, 3 piscines',
        address: 'Antanamitarana, Andilana',
        city: 'Nosy Be',
        district: 'Andilana',
        region: 'Diana',
        latitude: -13.3280,
        longitude: 48.1780,
        phone: '+261 38 06 400 44',
        website: 'https://www.royalandilana.com',
        coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        rating: 4.7,
        reviewCount: 312,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g9859532-d26530687-Reviews-Royal_Andilana_Resort_Spa-Andilana_Nosy_Be_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 5,
          hotelType: 'resort',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'gym', 'bar', 'plage_privee', 'room_service', 'plongee'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 600000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: "L'Heure Bleue",
        slug: 'lheure-bleue-nosy-be',
        description: "Lodge éco-chic en bord de plage de Madirokely. 2 piscines dont une à débordement, bungalows bohèmes, restaurant Le Deck supervisé par le chef Fameno Mantief. Ambiance zen, yoga et bien-être. Certifié Green Globe.",
        shortDescription: 'Lodge éco-chic, plage Madirokely, restaurant Le Deck',
        address: 'Madirokely Plage, BP 372',
        city: 'Nosy Be',
        district: 'Madirokely',
        region: 'Diana',
        latitude: -13.4100,
        longitude: 48.2350,
        phone: '+261 34 50 484 25',
        website: 'https://heurebleue.com',
        coverImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
        rating: 4.6,
        reviewCount: 278,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://heurebleue.com/en/',
        sourceAttribution: 'Site officiel',
        hotel: {
          starRating: 4,
          hotelType: 'lodge',
          amenities: ['wifi', 'generator', 'pool', 'restaurant', 'spa', 'ac', 'bar', 'plage', 'yoga', 'eco_certifie'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 280000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Chez Angeline',
        slug: 'chez-angeline-nosy-be',
        description: "Restaurant incontournable de Nosy Be, cuisine fraîche quotidienne préparée par un chef napolitain et romain. Pizzas considérées parmi les meilleures de l'île, plats italiens, français et malgaches. Personnel chaleureux et ambiance familiale.",
        shortDescription: 'Cuisine italienne-malgache, chef napolitain, meilleures pizzas',
        address: 'Ambatoloaka',
        city: 'Nosy Be',
        district: 'Ambatoloaka',
        region: 'Diana',
        latitude: -13.4060,
        longitude: 48.2560,
        phone: '+261 32 07 555 12',
        coverImage: 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=800',
        rating: 4.5,
        reviewCount: 345,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g479206-d3371631-Reviews-Chez_Angeline-Nosy_Be_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'pizza', 'malgache', 'français'],
          priceRange: 'MODERATE',
          avgMainCourse: 30000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },

      // =============================================
      // DIEGO SUAREZ - RESTAURANTS & HÔTELS (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Le Grand Hôtel Diego',
        slug: 'le-grand-hotel-diego-suarez',
        description: "Hôtel historique au cœur de Diego Suarez, 46 Rue Colbert. Casino, piscine extérieure, restaurant, jardin et salon partagé. Position centrale idéale pour explorer la ville. Charme colonial et ambiance conviviale.",
        shortDescription: 'Hôtel historique Rue Colbert, casino et piscine',
        address: '46 Rue Colbert',
        city: 'Diego Suarez',
        district: 'Centre-ville',
        region: 'Diana',
        latitude: -12.2717,
        longitude: 49.2930,
        phone: '+261 32 40 891 43',
        coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        rating: 4.0,
        reviewCount: 267,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g298270-d1751019-Reviews-Le_Grand_Hotel_Diego-Antsiranana_Diego_Suarez_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'bar', 'casino', 'jardin'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 120000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Mantasaly Resort',
        slug: 'mantasaly-resort-diego-suarez',
        description: "Resort éco-luxe 4 étoiles dans la baie préservée d'Andovokonko, 45 minutes de Diego Suarez. Baie privée, plage de sable blanc, excursions nature. Expérience exclusive et isolée au cœur de la nature malgache.",
        shortDescription: 'Resort éco-luxe, baie privée d\'Andovokonko',
        address: 'Andovokonko Bay, Ankorikakely',
        city: 'Diego Suarez',
        district: 'Andovokonko',
        region: 'Diana',
        latitude: -12.2200,
        longitude: 49.3500,
        phone: '+261 32 03 166 01',
        website: 'https://www.mantasaly.com',
        coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
        rating: 4.5,
        reviewCount: 198,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g298270-d8829817-Reviews-Mantasaly_Resort-Antsiranana_Diego_Suarez_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 4,
          hotelType: 'resort',
          amenities: ['wifi', 'generator', 'restaurant', 'spa', 'bar', 'plage_privee', 'plongee', 'kayak', 'excursions'],
          checkInTime: '12:00',
          checkOutTime: '10:00',
          lowestPrice: 450000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Suarez Hotel',
        slug: 'le-suarez-hotel-diego-suarez',
        description: "Hôtel avec vue panoramique sur la baie de Diego et les montagnes. Chambres spacieuses avec terrasse et moustiquaire, piscine, restaurant excellent, et un lémurien résident. Emplacement légèrement excentré mais tranquille.",
        shortDescription: 'Vue panoramique baie de Diego, piscine et restaurant',
        address: 'Diego Suarez',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.2650,
        longitude: 49.2900,
        phone: '+261 32 07 342 56',
        website: 'https://www.suarezhotel.com',
        coverImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        rating: 4.3,
        reviewCount: 234,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g298270-d2290315-Reviews-Le_Suarez_Hotel-Antsiranana_Diego_Suarez_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'ac', 'tv', 'bar', 'vue_panoramique'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 150000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Abakao Restaurant',
        slug: 'abakao-restaurant-diego-suarez',
        description: "Restaurant-bungalows sur la plage d'Abakao à Diego Suarez. Pizzas exceptionnelles considérées parmi les meilleures de la ville, hospitalité chaleureuse d'Helena et son équipe. Ambiance pieds dans le sable, fruits de mer frais.",
        shortDescription: 'Restaurant plage, meilleures pizzas de Diego Suarez',
        address: 'Plage de Abakao',
        city: 'Diego Suarez',
        district: 'Abakao',
        region: 'Diana',
        latitude: -12.2850,
        longitude: 49.3050,
        phone: '+261 32 04 567 89',
        coverImage: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
        rating: 4.8,
        reviewCount: 156,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g298270-d10672485-Reviews-Abakao_Hotel_Restaurant-Antsiranana_Diego_Suarez_Antsiranana_Province.html',
        sourceAttribution: 'TripAdvisor',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['pizza', 'fruits de mer', 'malgache'],
          priceRange: 'MODERATE',
          avgMainCourse: 25000,
          avgBeer: 7000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: false,
          hasWifi: false,
        },
      },

      // =============================================
      // TULÉAR / IFATY / ANAKAO (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Victory Hotel & Restaurant',
        slug: 'victory-hotel-tulear',
        description: "Hôtel 3 étoiles à l'entrée de Tuléar sur la RN7, à 5 minutes de l'aéroport. Piscine, restaurant, parking. Bon rapport qualité-prix pour une escale dans le sud-ouest. Chambres confortables avec climatisation.",
        shortDescription: 'Hôtel 3 étoiles, entrée de Tuléar, piscine',
        address: 'RN 7 - Andabizy',
        city: 'Toliara',
        district: 'Andabizy',
        region: 'Atsimo-Andrefana',
        latitude: -23.3450,
        longitude: 43.6800,
        phone: '+261 20 94 440 64',
        website: 'https://hotelvictory-mdg.com',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        rating: 4.0,
        reviewCount: 187,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g1826204-d1773495-Reviews-Victory_Hotel_Restaurant_Tulear-Toliara_Toliara_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'ac', 'tv', 'bar'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 100000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Vovo Telo Lodge',
        slug: 'vovo-telo-lodge-ifaty',
        description: "Lodge en bord de plage d'Ifaty, à 100 mètres de la mer. Piscine extérieure, parking privé, jardin tropical et accès plage privée. Bungalows confortables dans un cadre paisible face au lagon.",
        shortDescription: 'Lodge pieds dans l\'eau, Ifaty Beach',
        address: 'Mangily Ifaty',
        city: 'Ifaty',
        district: 'Mangily',
        region: 'Atsimo-Andrefana',
        latitude: -23.1550,
        longitude: 43.6100,
        phone: '+261 34 07 890 12',
        website: 'https://www.vovotelolodge.mg',
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        rating: 4.3,
        reviewCount: 178,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.booking.com/hotel/mg/vovo-telo-lodge.html',
        sourceAttribution: 'Booking.com',
        hotel: {
          starRating: 3,
          hotelType: 'lodge',
          amenities: ['wifi', 'generator', 'parking', 'pool', 'restaurant', 'bar', 'plage_privee', 'jardin'],
          checkInTime: '13:00',
          checkOutTime: '11:00',
          lowestPrice: 150000,
        },
      },

      // =============================================
      // MAHAJANGA / MAJUNGA (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Coco Lodge Majunga',
        slug: 'coco-lodge-majunga',
        description: "Hôtel 3 étoiles de 18 chambres au centre-ville de Mahajanga, entre la gendarmerie et le tribunal, à 200m du front de mer. Piscine, bar-lounge, restaurant gourmand réputé pour son plateau de fruits de mer. Services tour-opérateur intégrés.",
        shortDescription: 'Hôtel 3 étoiles centre-ville, restaurant fruits de mer',
        address: '49 Avenue de France',
        city: 'Mahajanga',
        district: 'Centre-ville',
        region: 'Boeny',
        latitude: -15.7167,
        longitude: 46.3167,
        phone: '+261 34 07 011 11',
        website: 'https://www.cocolodgemajunga-madagascar.com',
        coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        rating: 4.3,
        reviewCount: 287,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g303985-d1028270-Reviews-Coco_Lodge-Mahajanga_Mahajanga_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'pool', 'restaurant', 'bar', 'tour_operator', 'seminaire'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 150000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Antsanitia Resort',
        slug: 'antsanitia-resort-mahajanga',
        description: "Écolodge surplombant l'estuaire de la rivière Morira et le Canal du Mozambique, 25 minutes de l'aéroport de Mahajanga. Bungalows écologiques, piscine, restaurant, excursions nature. Un havre de paix entre terre et mer.",
        shortDescription: 'Écolodge vue estuaire, excursions nature',
        address: 'Fokontany d\'Antsanitia, Commune rurale de Belobaka',
        city: 'Mahajanga',
        district: 'Belobaka',
        region: 'Boeny',
        latitude: -15.6500,
        longitude: 46.2300,
        phone: '+261 32 03 911 11',
        website: 'http://antsanitia.com',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
        rating: 4.5,
        reviewCount: 198,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g303985-d2061861-Reviews-Antsanitia_Resort-Mahajanga_Mahajanga_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'ecolodge',
          amenities: ['wifi', 'generator', 'pool', 'restaurant', 'bar', 'excursions', 'vue_mer', 'kayak'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 200000,
        },
      },

      // =============================================
      // SAINTE-MARIE (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Mantis Soanambo Hotel & Spa',
        slug: 'mantis-soanambo-sainte-marie',
        description: "Boutique retreat du groupe Accor/Mantis sur l'île Sainte-Marie. 48 chambres supérieures avec vue océan Indien, jardin tropical luxuriant. Spa avec pratiques malgaches traditionnelles et huiles essentielles. Excursions baleines, snorkeling, visites de villages.",
        shortDescription: 'Resort Mantis/Accor, spa traditionnel, excursions baleines',
        address: 'Vohilava, PO Box 20',
        city: 'Sainte-Marie',
        district: 'Vohilava',
        region: 'Analanjirofo',
        latitude: -16.8600,
        longitude: 49.9300,
        phone: '+261 34 201 50 58',
        website: 'https://www.mantiscollection.com/hotel/mantis-soanambo-madagascar-resort-hotel/',
        coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
        rating: 4.4,
        reviewCount: 312,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mantiscollection.com/hotel/mantis-soanambo-madagascar-resort-hotel/',
        sourceAttribution: 'Mantis Collection',
        hotel: {
          starRating: 4,
          hotelType: 'resort',
          amenities: ['wifi', 'generator', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'bar', 'plage', 'excursions_baleines', 'plongee'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 400000,
        },
      },

      // =============================================
      // RANOMAFANA (vérifiés)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Setam Lodge',
        slug: 'setam-lodge-ranomafana',
        description: "Lodge confortable sur la RN26 à 10km de Ranomafana. 21 chambres avec eau chaude, proche du parc national. WiFi au restaurant, ambiance familiale en pleine nature. Base idéale pour l'observation des lémuriens au parc national.",
        shortDescription: 'Lodge nature proche parc national, observation lémuriens',
        address: 'RN 26, Km. 10',
        city: 'Ranomafana',
        district: null,
        region: 'Vatovavy-Fitovinany',
        latitude: -21.2500,
        longitude: 47.4500,
        phone: '+261 34 07 324 33',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.3,
        reviewCount: 167,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g316109-d1049215-Reviews-Setam_Lodge-Ranomafana_Fianarantsoa_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'lodge',
          amenities: ['wifi', 'generator', 'restaurant', 'excursions', 'jardin'],
          checkInTime: '13:00',
          checkOutTime: '11:00',
          lowestPrice: 160000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel Thermal Ranomafana',
        slug: 'hotel-thermal-ranomafana',
        description: "Hôtel 3 étoiles restauré avec 21 chambres confortables et restaurant gastronomique, dans une atmosphère sylvestre près des thermes et du parc national de Ranomafana. Jardin verdoyant, sources thermales à proximité.",
        shortDescription: 'Hôtel 3 étoiles, thermes et parc national à proximité',
        address: 'Ranomafana',
        city: 'Ranomafana',
        district: null,
        region: 'Vatovavy-Fitovinany',
        latitude: -21.2560,
        longitude: 47.4560,
        phone: '+261 34 05 678 90',
        website: 'https://www.thermal-ranomafana.mg',
        coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
        rating: 4.0,
        reviewCount: 145,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g316109-d11812211-Reviews-Hotel_Thermal_Ranomafana-Ranomafana_Fianarantsoa_Province.html',
        sourceAttribution: 'TripAdvisor',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['wifi', 'generator', 'restaurant', 'thermes', 'jardin'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
          lowestPrice: 120000,
        },
      },

      // =============================================
      // ATTRACTIONS TOURISTIQUES (vérifiées)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National de Ranomafana',
        slug: 'parc-national-ranomafana',
        description: "Parc national classé UNESCO abritant 12 espèces de lémuriens, dont le rare hapalémur doré. Forêt tropicale humide avec cascades, piscines naturelles et sources thermales. Circuit de 2 à 6 heures avec guide obligatoire.",
        shortDescription: 'Parc UNESCO, 12 espèces de lémuriens, forêt tropicale',
        address: 'RN 25, Ranomafana',
        city: 'Ranomafana',
        district: null,
        region: 'Vatovavy-Fitovinany',
        latitude: -21.2500,
        longitude: 47.4200,
        phone: '+261 34 05 000 00',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.7,
        reviewCount: 567,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Ranomafana_National_Park.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '3-6 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Montagne d\'Ambre',
        slug: 'montagne-dambre-diego-suarez',
        description: "Parc national de forêt tropicale humide au nord de Madagascar, à 30km de Diego Suarez. Cascades spectaculaires, lacs volcaniques, 7 espèces de lémuriens, caméléons et oiseaux endémiques. Climat frais et agréable même en été.",
        shortDescription: 'Forêt tropicale, cascades et lacs volcaniques près de Diego',
        address: 'Route de Joffreville',
        city: 'Diego Suarez',
        district: 'Joffreville',
        region: 'Diana',
        latitude: -12.5333,
        longitude: 49.1667,
        phone: '+261 32 04 000 00',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.6,
        reviewCount: 423,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Montagne_Ambre.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '4-6 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Les Tsingy Rouge',
        slug: 'tsingy-rouge-diego-suarez',
        description: "Formation géologique unique de grès rouge sculptée par l'érosion, à 45 minutes de Diego Suarez. Paysage lunaire spectaculaire, différent des Tsingy de Bemaraha. Accessible en 4x4, visite libre d'environ 1 heure.",
        shortDescription: 'Formations géologiques rouges uniques, paysage lunaire',
        address: 'Route d\'Ankarana',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.3667,
        longitude: 49.1833,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800',
        rating: 4.5,
        reviewCount: 345,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Tsingy_Rouge.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 25000,
          duration: '1-2 heures',
          bestTimeToVisit: 'Mai à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Réserve Spéciale Ankarana',
        slug: 'reserve-ankarana-diego-suarez',
        description: "Réserve naturelle avec tsingy gris, grottes, forêt sèche et lacs souterrains. 11 espèces de lémuriens, crocodiles, fossa. Circuits de difficulté variable, du débutant à l'expert. À 100km au sud de Diego Suarez.",
        shortDescription: 'Tsingy gris, grottes et lémuriens, circuits variés',
        address: 'RN6, Ankarana',
        city: 'Diego Suarez',
        district: 'Ankarana',
        region: 'Diana',
        latitude: -12.9500,
        longitude: 49.0833,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800',
        rating: 4.7,
        reviewCount: 456,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Ankarana.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '4-8 heures',
          bestTimeToVisit: 'Mai à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Mer d\'Émeraude',
        slug: 'mer-demeraude-diego-suarez',
        description: "Lagon aux eaux turquoise cristallines accessible uniquement en bateau depuis Diego Suarez. Banc de sable blanc immaculé, snorkeling exceptionnel, pique-nique sur l'île. L'une des plus belles excursions de Madagascar.",
        shortDescription: 'Lagon turquoise, banc de sable blanc, snorkeling',
        address: 'Baie de Diego Suarez',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.1833,
        longitude: 49.2333,
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        rating: 4.8,
        reviewCount: 534,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Emerald_Sea.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'beach',
          entryFee: 0,
          duration: 'Journée complète',
          bestTimeToVisit: 'Avril à Décembre',
          isFree: true,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National d\'Andasibe-Mantadia',
        slug: 'parc-national-andasibe',
        description: "Le parc national le plus accessible depuis Tana (3h de route). Habitat de l'Indri-Indri, le plus grand lémurien vivant, au cri emblématique. Forêt tropicale humide, caméléons, oiseaux endémiques. Visite nocturne possible.",
        shortDescription: 'Habitat de l\'Indri-Indri, le plus grand lémurien',
        address: 'RN2, Andasibe',
        city: 'Andasibe',
        district: null,
        region: 'Alaotra-Mangoro',
        latitude: -18.9333,
        longitude: 48.4167,
        phone: '+261 34 05 000 01',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.7,
        reviewCount: 678,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Andasibe_Mantadia.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '3-5 heures',
          bestTimeToVisit: 'Toute l\'année',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Réserve de Lokobe',
        slug: 'reserve-lokobe-nosy-be',
        description: "Dernière forêt primaire de Nosy Be, réserve naturelle intégrale. Lémuriens noirs (Eulemur macaco), caméléons, boas, plantes médicinales. Accessible uniquement en pirogue et à pied avec guide. Immersion totale en nature.",
        shortDescription: 'Dernière forêt primaire de Nosy Be, lémuriens noirs',
        address: 'Sud-est de Nosy Be',
        city: 'Nosy Be',
        district: 'Lokobe',
        region: 'Diana',
        latitude: -13.4167,
        longitude: 48.3167,
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.5,
        reviewCount: 312,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Attraction_Review-Lokobe_Reserve.html',
        sourceAttribution: 'TripAdvisor',
        attraction: {
          attractionType: 'park',
          entryFee: 55000,
          duration: '3-4 heures',
          bestTimeToVisit: 'Mai à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
    ];

    // Insert each establishment, skipping duplicates
    for (const est of establishments) {
      // Check if slug already exists
      const existing = await prisma.establishment.findFirst({
        where: { slug: est.slug },
      });

      if (existing) {
        created.skipped++;
        continue;
      }

      const { restaurant, hotel, attraction, ...establishmentData } = est as any;

      const data: any = {
        ...establishmentData,
        metaTitle: `${est.name} - ${est.city} | Mada Spot Bons Plans`,
        metaDescription: (est as any).shortDescription || est.description.substring(0, 155),
      };

      if (est.type === 'RESTAURANT' && restaurant) {
        data.restaurant = {
          create: {
            category: restaurant.category,
            cuisineTypes: JSON.stringify(restaurant.cuisineTypes || []),
            priceRange: restaurant.priceRange,
            avgMainCourse: restaurant.avgMainCourse || null,
            avgBeer: restaurant.avgBeer || null,
            hasDelivery: restaurant.hasDelivery || false,
            hasTakeaway: restaurant.hasTakeaway || false,
            hasReservation: restaurant.hasReservation || false,
            hasWifi: restaurant.hasWifi || false,
            openingHours: restaurant.openingHours ? JSON.stringify(restaurant.openingHours) : null,
          },
        };
        created.restaurants++;
      } else if (est.type === 'HOTEL' && hotel) {
        data.hotel = {
          create: {
            starRating: hotel.starRating || 3,
            hotelType: hotel.hotelType || 'hotel',
            amenities: JSON.stringify(hotel.amenities || []),
            checkInTime: hotel.checkInTime || '14:00',
            checkOutTime: hotel.checkOutTime || '11:00',
          },
        };
        created.hotels++;
      } else if (est.type === 'ATTRACTION' && attraction) {
        data.attraction = {
          create: {
            attractionType: attraction.attractionType || 'landmark',
            entryFeeForeign: attraction.entryFee || null,
            visitDuration: attraction.duration || null,
            bestTimeToVisit: attraction.bestTimeToVisit || null,
            isFree: attraction.isFree || false,
            hasGuide: attraction.guidedTourAvailable || false,
          },
        };
        created.attractions++;
      }

      await prisma.establishment.create({ data });
    }

    return NextResponse.json({
      success: true,
      message: `Sourcing vérifié terminé ! ${created.restaurants} restaurants, ${created.hotels} hôtels, ${created.attractions} attractions importés. ${created.skipped} doublons ignorés.`,
      created,
      note: 'Tous les établissements sont en statut "pending_review" pour modération admin.',
    });
  } catch (error: unknown) {
    logger.error('Seed verified error:', error);
    const message = error instanceof Error ? error.message : 'Erreur inconnue';
    return NextResponse.json(
      { error: message },
      { status: 500 }
    );
  }
}
