import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

import { logger } from '@/lib/logger';
// Seed Sources Touristiques - Établissements sourcés depuis :
// - mada-hotels-restos.fr (Hôtels & Restaurants)
// - Madagascar National Parks / MNP (Parcs Nationaux)
// - Office National du Tourisme de Madagascar / ONTM (Attractions)
// Tous en statut "pending_review" pour modération admin

export async function POST() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Non autorisé en production' }, { status: 403 });
  }

  try {
    let created = { restaurants: 0, hotels: 0, attractions: 0, skipped: 0 };

    const establishments = [
      // =============================================
      // HOTELS (Source: mada-hotels-restos.fr)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Vakona Forest Lodge',
        slug: 'vakona-forest-lodge-andasibe',
        description: "Le lodge le plus réputé de la région d'Andasibe, célèbre pour son île aux lémuriens où les visiteurs interagissent avec des lémuriens semi-sauvages. Bungalows confortables en bois au milieu d'une forêt tropicale luxuriante, piscine, lac pour canoë, sentiers nature et restaurant gastronomique. Base idéale pour explorer le parc national d'Andasibe-Mantadia.",
        shortDescription: 'Lodge réputé à Andasibe, île aux lémuriens, forêt tropicale',
        address: 'Route d\'Andasibe, Andasibe',
        city: 'Andasibe',
        district: null,
        region: 'Alaotra-Mangoro',
        latitude: -18.9300,
        longitude: 48.4200,
        phone: '+261 20 56 832 02',
        coverImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80',
        rating: 4.5,
        reviewCount: 620,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 4,
          hotelType: 'lodge',
          amenities: ['piscine', 'restaurant', 'île aux lémuriens', 'canoë', 'sentiers nature', 'bar', 'parking'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Ravintsara Wellness Hotel',
        slug: 'ravintsara-wellness-hotel-nosy-be',
        description: "Hôtel wellness haut de gamme à Nosy Be, niché dans des jardins tropicaux luxuriants avec vue sur la mer. Spa complet, piscine à débordement, centre de bien-être, restaurant gastronomique et bungalows élégants. L'adresse idéale pour combiner détente et découverte de l'île aux parfums.",
        shortDescription: 'Hôtel wellness 4*, spa, piscine à débordement, Nosy Be',
        address: 'Nosy Be',
        city: 'Nosy Be',
        district: null,
        region: 'Diana',
        latitude: -13.3500,
        longitude: 48.2600,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        rating: 4.4,
        reviewCount: 280,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 4,
          hotelType: 'resort',
          amenities: ['spa', 'piscine à débordement', 'restaurant', 'wellness center', 'jardins tropicaux', 'vue mer', 'bar'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel Talinjoo',
        slug: 'hotel-talinjoo-fort-dauphin',
        description: "L'hôtel de référence à Fort-Dauphin, perché sur une colline avec vue panoramique spectaculaire sur la baie de Libanona et l'océan Indien. Piscine, restaurant gastronomique, spa et chambres élégantes. Point de départ idéal pour la réserve de Berenty et les plages sauvages du sud-est.",
        shortDescription: 'Hôtel 4* panoramique, vue baie de Libanona, Fort-Dauphin',
        address: 'Fort-Dauphin',
        city: 'Fort-Dauphin',
        district: null,
        region: 'Anosy',
        latitude: -25.0300,
        longitude: 46.9800,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
        rating: 4.3,
        reviewCount: 190,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 4,
          hotelType: 'hotel',
          amenities: ['piscine', 'restaurant', 'spa', 'vue panoramique', 'bar', 'parking'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Paradisier',
        slug: 'le-paradisier-ifaty',
        description: "Resort balnéaire établi sur la côte sud-ouest près d'Ifaty, avec bungalows en bord de plage, piscine, centre de plongée et restaurant. Face au Grand Récif de Tuléar, troisième plus grand système récifal au monde. Idéal pour le snorkeling, la plongée et la découverte de la forêt épineuse.",
        shortDescription: 'Resort balnéaire, plongée sur le Grand Récif, Ifaty',
        address: 'Mangily-Ifaty',
        city: 'Tuléar',
        district: 'Ifaty',
        region: 'Atsimo-Andrefana',
        latitude: -23.1500,
        longitude: 43.6100,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        rating: 4.2,
        reviewCount: 210,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'resort',
          amenities: ['piscine', 'plage privée', 'restaurant', 'centre de plongée', 'bar', 'excursions'],
          checkInTime: '14:00',
          checkOutTime: '10:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Bakuba Lodge',
        slug: 'bakuba-lodge-ifaty',
        description: "Lodge de charme en bord de mer à Ifaty, spécialisé dans la plongée et le snorkeling sur le Grand Récif. Bungalows face à la mer, ambiance décontractée, restaurant de fruits de mer et proximité immédiate du récif corallien. Parfait pour les amateurs de vie marine.",
        shortDescription: 'Lodge plongée & snorkeling face au Grand Récif, Ifaty',
        address: 'Ifaty',
        city: 'Tuléar',
        district: 'Ifaty',
        region: 'Atsimo-Andrefana',
        latitude: -23.1400,
        longitude: 43.6000,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
        rating: 4.1,
        reviewCount: 170,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'lodge',
          amenities: ['plage', 'restaurant', 'plongée', 'snorkeling', 'bar'],
          checkInTime: '14:00',
          checkOutTime: '10:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Boraha Village',
        slug: 'boraha-village-sainte-marie',
        description: "Resort balnéaire à Sainte-Marie avec bungalows individuels dans un jardin tropical en bord de plage. Restaurant, excursions, plongée et observation des baleines à bosse (juillet-septembre). Ambiance paisible et romantique sur l'île aux pirates.",
        shortDescription: 'Resort balnéaire en bord de plage, Île Sainte-Marie',
        address: 'Île Sainte-Marie',
        city: 'Sainte-Marie',
        district: null,
        region: 'Analanjirofo',
        latitude: -16.8500,
        longitude: 49.9200,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        rating: 4.0,
        reviewCount: 150,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'resort',
          amenities: ['plage', 'restaurant', 'plongée', 'excursions baleines', 'jardin tropical', 'bar'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel Allamanda',
        slug: 'hotel-allamanda-diego-suarez',
        description: "Hôtel confortable entre Diego Suarez et la plage de Ramena, avec piscine, restaurant et bureau d'excursions. Position stratégique pour explorer la Mer d'Émeraude, la Montagne d'Ambre, les Tsingy Rouge et la Baie de Sakalava.",
        shortDescription: 'Hôtel entre Diego et Ramena, piscine, excursions',
        address: 'Route de Ramena',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.2800,
        longitude: 49.3000,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        rating: 4.0,
        reviewCount: 160,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['piscine', 'restaurant', 'excursions', 'parking', 'bar'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel Zomatel',
        slug: 'hotel-zomatel-fianarantsoa',
        description: "L'un des principaux hôtels de Fianarantsoa, base idéale pour explorer la Haute-Ville historique, les vignobles malgaches et le parc national de Ranomafana. Restaurant, salles de conférence et parking. Proche de la gare du train FCE vers Manakara.",
        shortDescription: 'Hôtel central à Fianarantsoa, base pour Ranomafana et FCE',
        address: 'Fianarantsoa',
        city: 'Fianarantsoa',
        district: null,
        region: 'Haute Matsiatra',
        latitude: -21.4400,
        longitude: 47.0800,
        phone: '+261 75 512 10',
        coverImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
        rating: 3.8,
        reviewCount: 120,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['restaurant', 'parking', 'salle de conférence', 'wifi'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel Neptune',
        slug: 'hotel-neptune-toamasina',
        description: "Hôtel en front de mer à Toamasina (Tamatave), la plus grande ville portuaire de Madagascar. Restaurant, terrasse avec vue sur l'océan Indien. Point de départ pour le Canal des Pangalanes et l'île de Nosy Mangabe.",
        shortDescription: 'Hôtel front de mer, Toamasina, porte du Canal des Pangalanes',
        address: 'Boulevard de la Libération, Toamasina',
        city: 'Toamasina',
        district: null,
        region: 'Atsinanana',
        latitude: -18.1500,
        longitude: 49.3900,
        phone: '+261 20 53 000 00',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        rating: 3.7,
        reviewCount: 95,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        hotel: {
          starRating: 3,
          hotelType: 'hotel',
          amenities: ['restaurant', 'vue mer', 'terrasse', 'wifi', 'parking'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },

      // =============================================
      // RESTAURANTS (Source: mada-hotels-restos.fr)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Kudeta Urban Restaurant',
        slug: 'kudeta-antananarivo',
        description: "Restaurant lounge tendance au cœur d'Antananarivo avec décor contemporain et ambiance cosmopolite. Cuisine fusion internationale mêlant influences françaises, asiatiques et malgaches. Cocktails créatifs, terrasse et soirées musicales le week-end.",
        shortDescription: 'Restaurant lounge fusion, ambiance tendance, Tana',
        address: 'Analakely, Antananarivo',
        city: 'Antananarivo',
        district: 'Analakely',
        region: 'Analamanga',
        latitude: -18.9100,
        longitude: 47.5250,
        phone: '+261 34 00 000 00',
        coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        rating: 4.2,
        reviewCount: 180,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['fusion', 'international', 'cocktails'],
          priceRange: 'MODERATE',
          avgMainCourse: 35000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
          openingHours: {
            monday: { open: '11:30', close: '23:00' },
            tuesday: { open: '11:30', close: '23:00' },
            wednesday: { open: '11:30', close: '23:00' },
            thursday: { open: '11:30', close: '23:00' },
            friday: { open: '11:30', close: '00:00' },
            saturday: { open: '11:30', close: '00:00' },
            sunday: { open: '11:30', close: '15:00' },
          },
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Rossini',
        slug: 'le-rossini-antananarivo',
        description: "Restaurant italien authentique au centre d'Antananarivo, réputé pour ses pizzas au feu de bois et ses pâtes fraîches maison. Cadre chaleureux, service attentionné et carte des vins italiens. L'une des meilleures tables italiennes de la capitale.",
        shortDescription: 'Italien authentique, pizzas au feu de bois, Tana',
        address: 'Antananarivo',
        city: 'Antananarivo',
        district: null,
        region: 'Analamanga',
        latitude: -18.9120,
        longitude: 47.5280,
        phone: '+261 34 00 000 00',
        coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        rating: 4.3,
        reviewCount: 220,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'pizza', 'pâtes'],
          priceRange: 'MODERATE',
          avgMainCourse: 30000,
          avgBeer: 8000,
          hasDelivery: true,
          hasTakeaway: true,
          hasReservation: true,
          hasWifi: true,
          openingHours: {
            monday: 'Fermé',
            tuesday: { open: '12:00', close: '14:30' },
            wednesday: { open: '12:00', close: '14:30' },
            thursday: { open: '12:00', close: '14:30' },
            friday: { open: '12:00', close: '14:30' },
            saturday: { open: '12:00', close: '22:30' },
            sunday: { open: '12:00', close: '14:30' },
          },
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Tsara Be',
        slug: 'le-tsara-be-diego-suarez',
        description: "Restaurant de fruits de mer réputé à Diego Suarez, spécialisé dans les produits frais de la baie : langoustes, crevettes géantes, calamars et poissons grillés. Terrasse avec vue, ambiance décontractée et prix accessibles pour une qualité exceptionnelle.",
        shortDescription: 'Fruits de mer frais, terrasse vue mer, Diego Suarez',
        address: 'Diego Suarez',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.2800,
        longitude: 49.2900,
        phone: '+261 32 07 000 00',
        coverImage: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800&q=80',
        rating: 4.3,
        reviewCount: 190,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.mada-hotels-restos.fr/',
        sourceAttribution: 'mada-hotels-restos.fr',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['fruits de mer', 'malgache', 'grillades'],
          priceRange: 'MODERATE',
          avgMainCourse: 25000,
          avgBeer: 7000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: false,
          openingHours: {
            monday: { open: '11:00', close: '21:30' },
            tuesday: { open: '11:00', close: '21:30' },
            wednesday: { open: '11:00', close: '21:30' },
            thursday: { open: '11:00', close: '21:30' },
            friday: { open: '11:00', close: '22:00' },
            saturday: { open: '11:00', close: '22:00' },
            sunday: { open: '11:00', close: '21:00' },
          },
        },
      },

      // =============================================
      // PARCS NATIONAUX (Source: Madagascar National Parks / MNP)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National de l\'Isalo',
        slug: 'parc-national-isalo',
        description: "L'un des parcs les plus visités de Madagascar avec son massif gréseux jurassique sculpté par l'érosion. Canyons profonds, piscines naturelles émeraude (Piscine Naturelle, Piscine Bleue), gorges bordées de palmiers, et la célèbre Fenêtre de l'Isalo pour un coucher de soleil inoubliable. Lémuriens, sifakas et oiseaux endémiques.",
        shortDescription: 'Massif gréseux, piscines naturelles, Fenêtre de l\'Isalo',
        address: 'Ranohira, RN7',
        city: 'Ranohira',
        district: null,
        region: 'Ihorombe',
        latitude: -22.5167,
        longitude: 45.3667,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.8,
        reviewCount: 890,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '3-8 heures (selon circuit)',
          bestTimeToVisit: 'Avril à Octobre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Tsingy de Bemaraha',
        slug: 'tsingy-de-bemaraha',
        description: "Site UNESCO spectaculaire avec ses forêts de pinacles calcaires acérés pouvant atteindre 50 mètres. Via ferrata avec ponts suspendus et harnais pour traverser le Grand Tsingy. Gorges du Manambolo navigables en pirogue, forêt sèche avec sifakas de Decken et lémuriens bruns. L'un des paysages les plus uniques au monde.",
        shortDescription: 'UNESCO, pinacles calcaires, via ferrata spectaculaire',
        address: 'Bekopaka',
        city: 'Bekopaka',
        district: null,
        region: 'Melaky',
        latitude: -18.6667,
        longitude: 44.8167,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
        rating: 4.9,
        reviewCount: 650,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '4-8 heures',
          bestTimeToVisit: 'Avril à Novembre (inaccessible en saison des pluies)',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National d\'Ankarafantsika',
        slug: 'parc-national-ankarafantsika',
        description: "Parc majeur du nord-ouest protégeant une forêt sèche caducifoliée, des lacs de cratère et des canyons de grès rouge. Lac Ravelobe avec l'aigle pêcheur de Madagascar (en danger critique). Sifakas de Coquerel, lémuriens mongoose et programme de reproduction de la tortue à soc. Accessible sur la RN4 vers Mahajanga.",
        shortDescription: 'Forêt sèche, aigle pêcheur, sifakas de Coquerel',
        address: 'Ampijoroa, RN4',
        city: 'Ampijoroa',
        district: null,
        region: 'Boeny',
        latitude: -16.3000,
        longitude: 46.8000,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.5,
        reviewCount: 320,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 45000,
          duration: '2-6 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National de Masoala',
        slug: 'parc-national-masoala',
        description: "Le plus grand parc national de Madagascar (230 000 ha), site UNESCO. Forêt tropicale primaire descendant jusqu'à la mer avec récifs coralliens. Lémuriens vari roux, aye-aye, baleines à bosse (juillet-septembre). Trois parcs marins inclus. L'un des endroits les plus sauvages et préservés de l'île.",
        shortDescription: 'UNESCO, plus grand parc, forêt tropicale et récifs coralliens',
        address: 'Presqu\'île de Masoala',
        city: 'Maroantsetra',
        district: null,
        region: 'Analanjirofo',
        latitude: -15.7000,
        longitude: 50.0000,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.7,
        reviewCount: 280,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '1-7 jours',
          bestTimeToVisit: 'Août à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National de Marojejy',
        slug: 'parc-national-marojejy',
        description: "Site UNESCO abritant l'un des primates les plus rares au monde : le sifaka soyeux (moins de 250 individus). Forêt tropicale pristine montant de 75m au sommet de 2 132m. Trek sur 3-5 jours à travers les camps d'altitude. Biodiversité exceptionnelle avec 275 espèces de fougères. Paradis des trekkeurs.",
        shortDescription: 'UNESCO, sifaka soyeux, trek d\'altitude exceptionnel',
        address: 'Manantenina',
        city: 'Andapa',
        district: null,
        region: 'SAVA',
        latitude: -14.4333,
        longitude: 49.7500,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.8,
        reviewCount: 180,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 65000,
          duration: '3-5 jours',
          bestTimeToVisit: 'Septembre à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Réserve de Berenty',
        slug: 'reserve-de-berenty',
        description: "Réserve privée mythique du sud, célèbre pour ses lémuriens catta extrêmement habitués et ses sifakas de Verreaux 'danseurs' qui approchent les visiteurs. Forêt-galerie de tamariniers et forêt épineuse unique avec Didierea et Alluaudia. Observation quasi garantie des lémuriens. Site de recherche primatologique de renommée mondiale.",
        shortDescription: 'Lémuriens habitués, sifakas danseurs, forêt épineuse',
        address: 'Amboasary-Sud',
        city: 'Fort-Dauphin',
        district: 'Amboasary-Sud',
        region: 'Anosy',
        latitude: -24.9833,
        longitude: 46.3000,
        phone: '+261 20 22 000 00',
        coverImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80',
        rating: 4.7,
        reviewCount: 520,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 60000,
          duration: '3-5 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc National de Zombitse-Vohibasia',
        slug: 'parc-national-zombitse-vohibasia',
        description: "Parc de forêt sèche transitionnelle sur la RN7 entre Tuléar et Isalo, réputé pour le birdwatching. Habitat exclusif du Bulbul d'Appert (en danger critique). Sifakas de Verreaux, lémuriens bruns et couas géants. Étape pratique sur la route du sud, facilement accessible.",
        shortDescription: 'Birdwatching exceptionnel, Bulbul d\'Appert, forêt sèche',
        address: 'RN7, près de Sakaraha',
        city: 'Sakaraha',
        district: null,
        region: 'Atsimo-Andrefana',
        latitude: -22.8833,
        longitude: 44.7000,
        phone: '+261 20 22 415 38',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.3,
        reviewCount: 140,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'park',
          entryFee: 45000,
          duration: '2-4 heures',
          bestTimeToVisit: 'Mai à Novembre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Massif du Makay',
        slug: 'massif-du-makay',
        description: "L'un des derniers 'mondes perdus' de la planète. Labyrinthe de canyons profonds jusqu'à 300m, gorges étroites, plateaux gréseux et forêts-galeries abritant une biodiversité endémique exceptionnelle. Peintures rupestres millénaires. Expéditions de 7-15 jours. Exploré scientifiquement depuis 2007 par Naturevolution.",
        shortDescription: 'Monde perdu, canyons profonds, expéditions aventure',
        address: 'Beroroha',
        city: 'Beroroha',
        district: null,
        region: 'Menabe',
        latitude: -21.6667,
        longitude: 44.6667,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.9,
        reviewCount: 85,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.parcs-madagascar.com/',
        sourceAttribution: 'Madagascar National Parks',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 35000,
          duration: '7-15 jours (expédition)',
          bestTimeToVisit: 'Avril à Octobre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },

      // =============================================
      // ATTRACTIONS MARINES & PLAGES (Source: ONTM)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Nosy Iranja',
        slug: 'nosy-iranja-nosy-be',
        description: "Deux îlots reliés par un banc de sable blanc immaculé de 1,5 km émergeant à marée basse. Classée parmi les plus belles plages du monde. Site de ponte des tortues marines vertes (novembre-février). Eaux turquoise cristallines et fonds coralliens intacts. Excursion incontournable depuis Nosy Be.",
        shortDescription: 'Banc de sable paradisiaque, tortues marines, Nosy Be',
        address: 'Au large de Nosy Be',
        city: 'Nosy Be',
        district: null,
        region: 'Diana',
        latitude: -13.5167,
        longitude: 47.9667,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        rating: 4.9,
        reviewCount: 450,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'beach',
          entryFee: 10000,
          duration: '4-6 heures (excursion journée)',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Nosy Tanikely',
        slug: 'nosy-tanikely-nosy-be',
        description: "Parc marin national depuis 2010 avec l'un des meilleurs spots de snorkeling de Madagascar. Plus de 100 espèces de poissons tropicaux, tortues marines, coraux intacts et un phare colonial historique. Réglementation stricte garantissant la préservation des fonds marins. Souvent combiné avec Nosy Komba en excursion journée.",
        shortDescription: 'Parc marin, snorkeling exceptionnel, tortues marines',
        address: 'Entre Nosy Be et Nosy Komba',
        city: 'Nosy Be',
        district: null,
        region: 'Diana',
        latitude: -13.4667,
        longitude: 48.2333,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        rating: 4.7,
        reviewCount: 380,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'beach',
          entryFee: 25000,
          duration: '3-5 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Nosy Komba',
        slug: 'nosy-komba-nosy-be',
        description: "L'île aux lémuriens, dominée par un sommet volcanique de 622m. Lémuriens macaco très habitués à l'homme, village d'Ampangorina célèbre pour ses nappes brodées et sculptures sur bois. Aucune route ni véhicule motorisé, atmosphère paisible et authentique. Bons récifs pour le snorkeling.",
        shortDescription: 'Île aux lémuriens, artisanat, atmosphère authentique',
        address: 'Entre Nosy Be et la Grande Terre',
        city: 'Nosy Be',
        district: null,
        region: 'Diana',
        latitude: -13.4500,
        longitude: 48.3500,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80',
        rating: 4.5,
        reviewCount: 340,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'beach',
          entryFee: 5000,
          duration: '3-5 heures',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Île aux Nattes',
        slug: 'ile-aux-nattes-sainte-marie',
        description: "Petit paradis tropical de 4 km² au sud de Sainte-Marie, accessible à pied à marée basse. Sans voiture, quasi sans électricité. Plages de sable blanc, récifs coralliens accessibles depuis le rivage, vieux phare désaffecté et cimetière de pirates du XVIIe siècle. Baleines visibles depuis le rivage en saison.",
        shortDescription: 'Paradis tropical sans voiture, pirates, Sainte-Marie',
        address: 'Sud de l\'Île Sainte-Marie',
        city: 'Sainte-Marie',
        district: null,
        region: 'Analanjirofo',
        latitude: -17.1667,
        longitude: 49.8500,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        rating: 4.6,
        reviewCount: 250,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'beach',
          entryFee: 0,
          duration: '2-6 heures',
          bestTimeToVisit: 'Avril à Novembre, Juillet-Septembre pour les baleines',
          isFree: true,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Anakao et Nosy Ve',
        slug: 'anakao-nosy-ve-tulear',
        description: "Village de pêcheurs Vezo authentique accessible uniquement par bateau depuis Tuléar. Nosy Ve, petite île corallienne au large, abrite l'une des seules colonies de phaétons à queue rouge de l'océan Indien occidental. Plages désertes, pirogues à balancier traditionnelles et immersion dans la culture Vezo.",
        shortDescription: 'Village Vezo, phaétons à queue rouge, bout du monde',
        address: 'Au sud de Tuléar (par bateau)',
        city: 'Tuléar',
        district: 'Anakao',
        region: 'Atsimo-Andrefana',
        latitude: -23.6500,
        longitude: 43.6500,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        rating: 4.5,
        reviewCount: 180,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'beach',
          entryFee: 10000,
          duration: 'Journée complète',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: false,
          guidedTourAvailable: false,
        },
      },

      // =============================================
      // ATTRACTIONS CULTURELLES (Source: ONTM)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Rova de Manjakamiadana',
        slug: 'rova-manjakamiadana-antananarivo',
        description: "Ancien palais royal des souverains merina, perché au sommet de la plus haute colline d'Antananarivo (1 468m). Résidence du pouvoir de 1610 à 1897. Construit en bois par Jean Laborde (1839), habillé de pierre par James Cameron (1867). Ravagé par un incendie en 1995, en cours de reconstruction. Panorama 360° exceptionnel sur la capitale.",
        shortDescription: 'Palais royal historique, panorama 360° sur Antananarivo',
        address: 'Colline d\'Analamanga, Haute-Ville',
        city: 'Antananarivo',
        district: 'Haute-Ville',
        region: 'Analamanga',
        latitude: -18.9200,
        longitude: 47.5236,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1580746738099-acb3a3a0e7c3?w=800&q=80',
        rating: 4.2,
        reviewCount: 280,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'cultural_site',
          entryFee: 10000,
          duration: '1-2 heures',
          bestTimeToVisit: 'Toute l\'année, Avril-Octobre pour le panorama',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Parc de Tsimbazaza',
        slug: 'parc-tsimbazaza-antananarivo',
        description: "Principal espace vert d'Antananarivo combinant jardin botanique, zoo et musée d'histoire naturelle. Lémuriens, reptiles endémiques, fossa, tortues radiata. Musée célèbre pour ses os d'oiseaux-éléphants (Aepyornis maximus), le plus grand oiseau ayant existé. Collections ethnographiques et fossiles de lémuriens géants.",
        shortDescription: 'Zoo, jardin botanique, musée paléontologique, Tana',
        address: 'Quartier de Tsimbazaza',
        city: 'Antananarivo',
        district: 'Tsimbazaza',
        region: 'Analamanga',
        latitude: -18.9381,
        longitude: 47.5194,
        phone: '+261 20 22 000 00',
        coverImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80',
        rating: 3.8,
        reviewCount: 320,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'park',
          entryFee: 10000,
          duration: '2-3 heures',
          bestTimeToVisit: 'Toute l\'année (fermé le lundi)',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Ambositra et villages Zafimaniry',
        slug: 'ambositra-zafimaniry',
        description: "Capitale malgache de l'artisanat du bois, réputée pour ses marqueteries et sculptures en palissandre. Les villages Zafimaniry voisins (UNESCO patrimoine immatériel 2003) perpétuent un art ancestral de construction en bois sans clous avec des motifs géométriques symboliques. Trek de 1-3 jours avec nuit chez l'habitant.",
        shortDescription: 'UNESCO artisanat bois, marqueterie, villages traditionnels',
        address: 'RN7, Ambositra',
        city: 'Ambositra',
        district: null,
        region: 'Amoron\'i Mania',
        latitude: -20.5167,
        longitude: 47.2333,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1580746738099-acb3a3a0e7c3?w=800&q=80',
        rating: 4.3,
        reviewCount: 190,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'cultural_site',
          entryFee: 0,
          duration: '1-3 jours (trek Zafimaniry)',
          bestTimeToVisit: 'Avril à Octobre',
          isFree: true,
          guidedTourAvailable: true,
        },
      },

      // =============================================
      // ATTRACTIONS NATURELLES (Source: ONTM)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Lac Tritriva',
        slug: 'lac-tritriva-antsirabe',
        description: "Lac de cratère volcanique aux eaux d'un bleu profond, encaissé dans des parois abruptes de 80-100m. Phénomène unique : le niveau monte en saison sèche et descend en saison des pluies. Légende des amoureux séparés transformés en deux arbres entrelacés au bord du cratère. À 17km d'Antsirabe.",
        shortDescription: 'Lac de cratère mystérieux, légende des amoureux, Antsirabe',
        address: 'À 17 km d\'Antsirabe',
        city: 'Antsirabe',
        district: null,
        region: 'Vakinankaratra',
        latitude: -19.9500,
        longitude: 46.9167,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=80',
        rating: 4.3,
        reviewCount: 210,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 10000,
          duration: '1-2 heures',
          bestTimeToVisit: 'Avril à Octobre',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Cirque Rouge',
        slug: 'cirque-rouge-diego-suarez',
        description: "Amphithéâtre naturel aux falaises multicolores (rouge, ocre, rose, violet, blanc) formé par l'érosion de grès et latérites. Spectacle chromatique extraordinaire en fin de journée quand la lumière rasante enflamme les couleurs. Formations en piliers et champignons. Sur la route de Ramena, à 12km de Diego Suarez.",
        shortDescription: 'Falaises multicolores, spectacle géologique, Diego Suarez',
        address: 'Route de Ramena',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.2667,
        longitude: 49.3667,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.4,
        reviewCount: 350,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 5000,
          duration: '30-45 minutes',
          bestTimeToVisit: 'Avril à Novembre, fin d\'après-midi',
          isFree: false,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Réserve Reniala',
        slug: 'reniala-arboretum-ifaty',
        description: "Éco-parc de 60 ha préservant la forêt épineuse endémique du sud-ouest avec baobabs millénaires (Adansonia rubrostipa, certains de plus de 1 200 ans), Didiereaceae, euphorbes et pachypodium. L'un des meilleurs sites pour observer le Long-tailed Ground Roller (endémique menacé) et le Subdesert Mesite.",
        shortDescription: 'Baobabs millénaires, forêt épineuse, oiseaux rares, Ifaty',
        address: 'Mangily-Ifaty',
        city: 'Tuléar',
        district: 'Mangily',
        region: 'Atsimo-Andrefana',
        latitude: -23.1333,
        longitude: 43.6000,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
        rating: 4.5,
        reviewCount: 280,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'park',
          entryFee: 15000,
          duration: '1-3 heures',
          bestTimeToVisit: 'Avril à Novembre, matin tôt pour les oiseaux',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Montagne des Français',
        slug: 'montagne-des-francais-diego-suarez',
        description: "Massif calcaire karstique culminant à 425m dominant la baie de Diego Suarez (2e plus grande baie naturelle du monde). Mini-tsingy, baobabs endémiques (A. suarezensis), lémuriens couronnés et plus petit caméléon du monde (Brookesia micra). Panorama 360° exceptionnel. Vestiges militaires de 1942.",
        shortDescription: 'Panorama baie de Diego, mini-tsingy, plus petit caméléon du monde',
        address: 'À 8 km de Diego Suarez',
        city: 'Diego Suarez',
        district: null,
        region: 'Diana',
        latitude: -12.3167,
        longitude: 49.3333,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.4,
        reviewCount: 290,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 10000,
          duration: '2-3 heures',
          bestTimeToVisit: 'Avril à Novembre, matin tôt',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Forêt de Kirindy',
        slug: 'foret-de-kirindy-morondava',
        description: "Meilleur endroit au monde pour observer le fossa (plus grand prédateur de Madagascar) et le lémurien souris de Madame Berthe (plus petit primate du monde, 30g). Forêt sèche caducifoliée avec sifakas danseurs, lémuriens nocturnes et geckos géants. Promenades nocturnes essentielles. À 60km de Morondava, souvent combiné avec l'Allée des Baobabs.",
        shortDescription: 'Fossa, plus petit primate du monde, marches nocturnes',
        address: 'À 60 km de Morondava',
        city: 'Morondava',
        district: null,
        region: 'Menabe',
        latitude: -20.0667,
        longitude: 44.6500,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.6,
        reviewCount: 310,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'park',
          entryFee: 30000,
          duration: '3-6 heures (jour + nuit)',
          bestTimeToVisit: 'Septembre à Novembre pour le fossa',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Grottes d\'Anjohibe',
        slug: 'grottes-anjohibe-mahajanga',
        description: "L'un des plus vastes réseaux spéléologiques d'Afrique australe. Salles immenses (50m de haut), stalactites et stalagmites monumentales, rivières souterraines, cascades et lacs internes. Site paléontologique majeur : fossiles de lémuriens géants disparus, hippopotames nains et tortues géantes. Forêt sèche et lac de cratère aux alentours.",
        shortDescription: 'Grottes monumentales, paléontologie, près de Mahajanga',
        address: 'À 80 km de Mahajanga',
        city: 'Mahajanga',
        district: null,
        region: 'Boeny',
        latitude: -15.5333,
        longitude: 46.8833,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.3,
        reviewCount: 120,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 20000,
          duration: '2-3 heures',
          bestTimeToVisit: 'Avril à Novembre (piste praticable)',
          isFree: false,
          guidedTourAvailable: true,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Canal des Pangalanes',
        slug: 'canal-des-pangalanes',
        description: "Système de voies navigables de 665 km le long de la côte est, composé de lagunes naturelles, lacs et canaux artificiels creusés entre 1896-1904. Navigation en pirogue à travers villages de pêcheurs, plantations de litchis et girofle, forêts de ravenala. Faune aquatique et forestière, immersion dans la vie rurale côtière betsimisaraka.",
        shortDescription: 'Voie navigable 665km, pirogues, vie rurale côte est',
        address: 'Côte est, de Mananjary à Toamasina',
        city: 'Toamasina',
        district: null,
        region: 'Atsinanana',
        latitude: -18.1500,
        longitude: 49.3800,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.4,
        reviewCount: 220,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 0,
          duration: '1-5 jours',
          bestTimeToVisit: 'Avril à Novembre',
          isFree: true,
          guidedTourAvailable: true,
        },
      },

      // =============================================
      // EXPÉRIENCES / ACTIVITÉS (Source: ONTM)
      // =============================================
      {
        type: 'ATTRACTION' as const,
        name: 'Train FCE Fianarantsoa-Manakara',
        slug: 'train-fce-fianarantsoa-manakara',
        description: "L'un des derniers trains de voyageurs de Madagascar, reliant Fianarantsoa à Manakara sur 163km. Prouesse d'ingénierie coloniale (1926-1936) traversant 67 tunnels et 67 ponts à travers la forêt tropicale. Voyage de 8-15h avec scènes de vie extraordinaires aux gares. L'une des expériences les plus mémorables de Madagascar.",
        shortDescription: 'Train historique, 67 tunnels, traversée forêt tropicale',
        address: 'Gare de Fianarantsoa',
        city: 'Fianarantsoa',
        district: null,
        region: 'Haute Matsiatra',
        latitude: -21.4400,
        longitude: 47.0800,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.5,
        reviewCount: 380,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'landmark',
          entryFee: 50000,
          duration: '8-15 heures',
          bestTimeToVisit: 'Avril à Octobre (mardi, jeudi, samedi)',
          isFree: false,
          guidedTourAvailable: false,
        },
      },
      {
        type: 'ATTRACTION' as const,
        name: 'Descente de la Tsiribihina',
        slug: 'descente-tsiribihina',
        description: "Aventure fluviale mythique de 2-3 jours en pirogue sur 150km. Gorges aux falaises calcaires blanches, forêts-galeries, sifakas dansant sur les berges, crocodiles du Nil, aigles pêcheurs. Bivouac sous les étoiles. Cascade des Nymphes pour la baignade. Premier tronçon de l'itinéraire Tsiribihina → Allée des Baobabs → Tsingy.",
        shortDescription: 'Aventure en pirogue 2-3 jours, faune, bivouac étoilé',
        address: 'De Miandrivazo à Belo-sur-Tsiribihina',
        city: 'Morondava',
        district: 'Miandrivazo',
        region: 'Menabe',
        latitude: -19.5167,
        longitude: 45.4667,
        phone: null,
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.7,
        reviewCount: 290,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.madagascar-tourisme.com/',
        sourceAttribution: 'Office National du Tourisme de Madagascar',
        attraction: {
          attractionType: 'natural_wonder',
          entryFee: 0,
          duration: '2-3 jours',
          bestTimeToVisit: 'Mai à Octobre',
          isFree: true,
          guidedTourAvailable: true,
        },
      },
    ];

    // =============================================
    // CRÉATION EN BASE
    // =============================================
    for (const est of establishments) {
      const existing = await prisma.establishment.findFirst({
        where: { slug: est.slug },
      });

      if (existing) {
        created.skipped++;
        continue;
      }

      const { restaurant, hotel, attraction, ...establishmentData } = est as any;

      const data: any = {
        ...establishmentData,
        metaTitle: `${est.name} - ${est.city} | Mada Spot Bons Plans`,
        metaDescription: (est as any).shortDescription || est.description.substring(0, 155),
      };

      if (est.type === 'RESTAURANT' && restaurant) {
        data.restaurant = {
          create: {
            category: restaurant.category,
            cuisineTypes: JSON.stringify(restaurant.cuisineTypes || []),
            priceRange: restaurant.priceRange,
            avgMainCourse: restaurant.avgMainCourse || null,
            avgBeer: restaurant.avgBeer || null,
            hasDelivery: restaurant.hasDelivery || false,
            hasTakeaway: restaurant.hasTakeaway || false,
            hasReservation: restaurant.hasReservation || false,
            hasWifi: restaurant.hasWifi || false,
            openingHours: restaurant.openingHours ? JSON.stringify(restaurant.openingHours) : null,
          },
        };
        created.restaurants++;
      } else if (est.type === 'HOTEL' && hotel) {
        data.hotel = {
          create: {
            starRating: hotel.starRating || 3,
            hotelType: hotel.hotelType || 'hotel',
            amenities: JSON.stringify(hotel.amenities || []),
            checkInTime: hotel.checkInTime || '14:00',
            checkOutTime: hotel.checkOutTime || '11:00',
          },
        };
        created.hotels++;
      } else if (est.type === 'ATTRACTION' && attraction) {
        data.attraction = {
          create: {
            attractionType: attraction.attractionType || 'landmark',
            entryFeeForeign: attraction.entryFee || null,
            visitDuration: attraction.duration || null,
            bestTimeToVisit: attraction.bestTimeToVisit || null,
            isFree: attraction.isFree || false,
            hasGuide: attraction.guidedTourAvailable || false,
          },
        };
        created.attractions++;
      }

      await prisma.establishment.create({ data });
    }

    return NextResponse.json({
      success: true,
      message: `Seed Sources terminé ! ${created.restaurants} restaurants, ${created.hotels} hôtels, ${created.attractions} attractions importés. ${created.skipped} doublons ignorés.`,
      created,
      sources: [
        'mada-hotels-restos.fr (Hôtels & Restaurants)',
        'Madagascar National Parks / MNP (Parcs Nationaux)',
        'Office National du Tourisme de Madagascar / ONTM (Attractions)',
      ],
      note: 'Tous les établissements sont en statut "pending_review" pour modération admin.',
    });
  } catch (error: unknown) {
    logger.error('Seed Sources error:', error);
    const message = error instanceof Error ? error.message : 'Erreur inconnue';
    return NextResponse.json(
      { error: message },
      { status: 500 }
    );
  }
}
