import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

import { logger } from '@/lib/logger';
// Agent de Sourcing Mada Spot - 50 établissements réels de Madagascar
// Statut: "pending_review" (En cours d'analyse) pour modération admin

export async function POST() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Non autorisé en production' }, { status: 403 });
  }

  try {
    let created = { restaurants: 0, hotels: 0, attractions: 0, skipped: 0 };

    const establishments = [
      // =============================================
      // ANTANANARIVO - RESTAURANTS
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'KoKo Lodge',
        slug: 'koko-lodge-antananarivo',
        description: "Restaurant gastronomique réputé d'Antananarivo, KoKo Lodge propose une cuisine malgache raffinée et française dans un cadre élégant avec terrasse jardin. Le filet de zébu, la langouste et les plats revisités de la cuisine malgache sont exceptionnels. Un des restaurants les mieux notés de la capitale.",
        shortDescription: 'Gastronomie malgache-française raffinée, terrasse jardin à Isoraka',
        address: 'Lot IVC 45, Rue Pierre Stibbe, Isoraka',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9150,
        longitude: 47.5310,
        phone: '+261 20 22 611 60',
        coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=800',
        rating: 4.5,
        reviewCount: 245,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293390-d2372057-Reviews-KoKo_Lodge-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'KoKo Lodge - Restaurant Gastronomique Antananarivo',
        metaDescription: 'Restaurant gastronomique malgache-français à Isoraka. Filet de zébu, langouste, terrasse jardin.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['malgache', 'français', 'gastronomique']),
          priceRange: 'UPSCALE' as const,
          openingHours: JSON.stringify({ lundi: { open: '12:00', close: '14:00' }, mardi: { open: '12:00', close: '14:00' }, mercredi: { open: '12:00', close: '14:00' }, jeudi: { open: '12:00', close: '22:00' }, vendredi: { open: '12:00', close: '22:00' }, samedi: { open: '12:00', close: '22:00' } }),
          hasReservation: true, hasWifi: true, hasParking: true, hasGenerator: true,
          specialties: JSON.stringify(['Filet de zébu', 'Langouste grillée', 'Cuisine malgache revisitée']),
          avgMainCourse: 60000, avgBeer: 10000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Café de la Gare',
        slug: 'cafe-de-la-gare-antananarivo',
        description: "Installé dans l'ancienne gare coloniale de Soarano magnifiquement restaurée, Le Café de la Gare est un lieu emblématique. Brasserie française avec touches malgaches, il propose zebu burgers, croque-monsieurs et bières artisanales dans une ambiance unique mêlant histoire et modernité.",
        shortDescription: 'Brasserie dans l\'ancienne gare coloniale de Soarano, ambiance unique',
        address: 'Gare de Soarano, Place de l\'Indépendance',
        city: 'Antananarivo',
        district: 'Soarano',
        region: 'Analamanga',
        latitude: -18.9065,
        longitude: 47.5240,
        phone: '+261 20 22 254 09',
        coverImage: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800',
        rating: 4.0,
        reviewCount: 198,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293390-d3578711-Reviews-Cafe_de_la_Gare-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Café de la Gare - Brasserie Antananarivo',
        metaDescription: 'Brasserie dans l\'ancienne gare coloniale de Soarano. Burgers, bières artisanales, ambiance historique.',
        restaurant: {
          category: 'CAFE' as const,
          cuisineTypes: JSON.stringify(['français', 'brasserie', 'malgache']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '08:00', close: '23:00' }, mardi: { open: '08:00', close: '23:00' }, mercredi: { open: '08:00', close: '23:00' }, jeudi: { open: '08:00', close: '23:00' }, vendredi: { open: '08:00', close: '00:00' }, samedi: { open: '08:00', close: '00:00' } }),
          hasWifi: true, hasGenerator: true,
          specialties: JSON.stringify(['Zebu burger', 'Croque-monsieur', 'Bières artisanales']),
          avgMainCourse: 25000, avgBeer: 8000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Nerone Ristorante',
        slug: 'nerone-ristorante-antananarivo',
        description: "Considéré comme le meilleur restaurant italien d'Antananarivo, Nerone est tenu par un chef italien passionné. Pizzas au feu de bois, pâtes fraîches maison et tiramisu divin. L'ambiance est chaleureuse et le service impeccable. Incontournable pour les amateurs de cuisine italienne.",
        shortDescription: 'Le meilleur italien de Tana, pizzas au feu de bois et pâtes maison',
        address: 'Rue Rainijohary, Isoraka',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9145,
        longitude: 47.5295,
        phone: '+261 20 22 625 71',
        coverImage: 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=800',
        rating: 4.5,
        reviewCount: 312,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293390-d3203873-Reviews-Nerone-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Nerone Ristorante - Restaurant Italien Antananarivo',
        metaDescription: 'Meilleur restaurant italien de Tana. Pizzas au feu de bois, pâtes fraîches, tiramisu. Chef italien.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['italien', 'pizza', 'méditerranéen']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ mardi: { open: '12:00', close: '14:30' }, mercredi: { open: '12:00', close: '14:30' }, jeudi: { open: '12:00', close: '22:30' }, vendredi: { open: '12:00', close: '22:30' }, samedi: { open: '12:00', close: '22:30' }, dimanche: { open: '12:00', close: '14:30' } }),
          hasReservation: true, hasWifi: true, hasParking: true,
          specialties: JSON.stringify(['Pizza margherita au feu de bois', 'Pâtes fraîches maison', 'Tiramisu']),
          avgMainCourse: 35000, avgBeer: 8000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Batavia',
        slug: 'batavia-antananarivo',
        description: "Café-restaurant moderne et branché, Batavia est le QG des expatriés et professionnels de Tana. Excellent café torréfié localement, pâtisseries maison, brunchs copieux et plats légers. WiFi rapide, cadre agréable et service soigné. Parfait pour un petit-déjeuner ou un déjeuner de travail.",
        shortDescription: 'Café branché, pâtisseries maison et brunch, QG des expats',
        address: 'Rue Rainitovo, Antsahavola',
        city: 'Antananarivo',
        district: 'Antsahavola',
        region: 'Analamanga',
        latitude: -18.9095,
        longitude: 47.5260,
        phone: '+261 34 05 622 22',
        coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        rating: 4.0,
        reviewCount: 167,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293390-d10350573-Reviews-Batavia-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Batavia - Café & Brunch Antananarivo',
        metaDescription: 'Café branché à Antsahavola. Pâtisseries maison, brunch, café local torréfié, WiFi rapide.',
        restaurant: {
          category: 'CAFE' as const,
          cuisineTypes: JSON.stringify(['café', 'brunch', 'pâtisseries']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '07:00', close: '22:00' }, mardi: { open: '07:00', close: '22:00' }, mercredi: { open: '07:00', close: '22:00' }, jeudi: { open: '07:00', close: '22:00' }, vendredi: { open: '07:00', close: '22:00' }, samedi: { open: '08:00', close: '22:00' } }),
          hasWifi: true, hasGenerator: true,
          specialties: JSON.stringify(['Café torréfié local', 'Croissants maison', 'Brunch du samedi']),
          avgMainCourse: 20000, avgBeer: 7000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Shangri-La',
        slug: 'shangri-la-antananarivo',
        description: "Restaurant chinois historique de Tana, le Shangri-La sert une cuisine cantonaise généreuse depuis des décennies. Dim sum, canard laqué, nouilles sautées et portions copieuses. Un classique pour les amateurs de cuisine asiatique à Madagascar.",
        shortDescription: 'Restaurant chinois historique de Tana, cuisine cantonaise généreuse',
        address: 'Rue Printsy Ratsimamanga',
        city: 'Antananarivo',
        region: 'Analamanga',
        latitude: -18.9125,
        longitude: 47.5248,
        phone: '+261 20 22 610 08',
        coverImage: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800',
        rating: 4.0,
        reviewCount: 134,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g293390-d3889857-Reviews-Shangri_La-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Shangri-La - Restaurant Chinois Antananarivo',
        metaDescription: 'Restaurant chinois historique de Tana. Cuisine cantonaise, dim sum, canard laqué.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['chinois', 'cantonais', 'asiatique']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '11:30', close: '14:30' }, mardi: { open: '11:30', close: '14:30' }, mercredi: { open: '11:30', close: '22:00' }, jeudi: { open: '11:30', close: '22:00' }, vendredi: { open: '11:30', close: '22:00' }, samedi: { open: '11:30', close: '22:00' }, dimanche: { open: '11:30', close: '14:30' } }),
          hasReservation: true, hasParking: true,
          specialties: JSON.stringify(['Dim sum', 'Canard laqué', 'Nouilles sautées']),
          avgMainCourse: 30000, avgBeer: 8000,
        },
      },
      // ANTANANARIVO - HOTELS
      {
        type: 'HOTEL' as const,
        name: 'Palissandre Hôtel & Spa',
        slug: 'palissandre-hotel-spa-antananarivo',
        description: "Hôtel de luxe moderne à Alarobia, le Palissandre offre un décor inspiré du bois de palissandre malgache. Spa haut de gamme, piscine sur le toit, restaurant gastronomique. Quartier calme et résidentiel, service 5 étoiles.",
        shortDescription: 'Hôtel luxe moderne à Alarobia, spa, piscine rooftop',
        address: 'Rue Ravoninahitriniarivo, Alarobia',
        city: 'Antananarivo',
        district: 'Alarobia',
        region: 'Analamanga',
        latitude: -18.9020,
        longitude: 47.5380,
        phone: '+261 20 22 444 00',
        coverImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        rating: 4.5,
        reviewCount: 287,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293390-d1915498-Reviews-Palissandre_Hotel_Spa-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Palissandre Hôtel & Spa - Luxe à Antananarivo',
        metaDescription: 'Hôtel de luxe à Alarobia, Tana. Spa, piscine rooftop, restaurant gastronomique. Décor palissandre.',
        hotel: {
          starRating: 4,
          hotelType: 'hotel de luxe',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'gym', 'bar', 'room_service']),
          checkInTime: '14:00', checkOutTime: '12:00',
          roomTypes: [
            { name: 'Chambre Deluxe', capacity: 2, pricePerNight: 280000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar']) },
            { name: 'Suite Junior', capacity: 2, pricePerNight: 500000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_ville', 'salon']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Tamboho Hotel',
        slug: 'tamboho-hotel-antananarivo',
        description: "Boutique hôtel 4 étoiles à Ambatobe, le Tamboho allie architecture malgache traditionnelle et confort moderne. Jardins luxuriants, piscine, restaurant excellent. Quartier résidentiel calme, service personnalisé et attentionné.",
        shortDescription: 'Boutique hôtel 4 étoiles, architecture malgache, jardins luxuriants',
        address: 'Ambatobe',
        city: 'Antananarivo',
        district: 'Ambatobe',
        region: 'Analamanga',
        latitude: -18.8950,
        longitude: 47.5450,
        phone: '+261 20 22 443 15',
        coverImage: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
        rating: 4.5,
        reviewCount: 198,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293390-d1496498-Reviews-Tamboho_Hotel-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Tamboho Hotel - Boutique Hôtel Antananarivo',
        metaDescription: 'Boutique hôtel 4 étoiles à Ambatobe. Architecture malgache, jardins, piscine, restaurant.',
        hotel: {
          starRating: 4,
          hotelType: 'boutique',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'ac', 'tv', 'bar', 'jardin']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Confort', capacity: 2, pricePerNight: 200000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Suite Tamboho', capacity: 2, pricePerNight: 400000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'terrasse']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Louvre Hôtel & Spa',
        slug: 'le-louvre-hotel-spa-antananarivo',
        description: "Hôtel 4 étoiles au cœur de Tsaralalana, Le Louvre offre des chambres modernes, un spa complet et un restaurant rooftop avec vue sur la ville. Position centrale idéale pour les voyageurs d'affaires.",
        shortDescription: 'Hôtel 4 étoiles central, spa et restaurant rooftop avec vue',
        address: 'Rue du Dr Raseta, Tsaralalana',
        city: 'Antananarivo',
        district: 'Tsaralalana',
        region: 'Analamanga',
        latitude: -18.9070,
        longitude: 47.5225,
        phone: '+261 20 22 234 50',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800',
        rating: 4.0,
        reviewCount: 156,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g293390-d1205894-Reviews-Le_Louvre_Hotel_Spa-Antananarivo',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Louvre Hôtel & Spa - Hôtel Central Antananarivo',
        metaDescription: 'Hôtel 4 étoiles central à Tsaralalana. Spa, restaurant rooftop, chambres modernes.',
        hotel: {
          starRating: 4,
          hotelType: 'hotel',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'restaurant', 'spa', 'ac', 'tv', 'bar']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 180000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Suite Executive', capacity: 2, pricePerNight: 380000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_ville']) },
          ],
        },
      },
      // =============================================
      // NOSY BE - RESTAURANTS
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Deck',
        slug: 'le-deck-nosy-be',
        description: "Restaurant français et fruits de mer avec terrasse face à l'océan à Ambatoloaka. Langouste grillée, poisson du jour, cuisine méditerranéenne raffinée. L'un des restaurants les mieux notés de Nosy Be.",
        shortDescription: 'Terrasse face à l\'océan, langouste et cuisine française à Nosy Be',
        address: 'Ambatoloaka',
        city: 'Nosy Be',
        district: 'Ambatoloaka',
        region: 'Diana',
        latitude: -13.4480,
        longitude: 48.2380,
        phone: '+261 32 07 139 39',
        coverImage: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
        rating: 4.5,
        reviewCount: 234,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurants-g479198-Nosy_Be',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Deck - Restaurant Fruits de Mer Nosy Be',
        metaDescription: 'Restaurant face à l\'océan à Nosy Be. Langouste grillée, poisson frais, cuisine française.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['français', 'fruits de mer', 'méditerranéen']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '10:00', close: '22:00' }, mardi: { open: '10:00', close: '22:00' }, mercredi: { open: '10:00', close: '22:00' }, jeudi: { open: '10:00', close: '22:00' }, vendredi: { open: '10:00', close: '22:00' }, samedi: { open: '10:00', close: '22:00' }, dimanche: { open: '10:00', close: '22:00' } }),
          hasReservation: true, hasWifi: true,
          specialties: JSON.stringify(['Langouste grillée', 'Poisson du jour', 'Plateau fruits de mer']),
          avgMainCourse: 45000, avgBeer: 8000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Table d\'Alexandre',
        slug: 'la-table-dalexandre-nosy-be',
        description: "Cuisine fusion franco-malgache raffinée, La Table d'Alexandre sublime les produits locaux avec des techniques françaises. Plats infusés à la vanille de Nosy Be, zébu flambé, desserts créatifs. Cadre intime et service soigné.",
        shortDescription: 'Fusion franco-malgache raffinée, vanille de Nosy Be',
        address: 'Route d\'Ambatoloaka',
        city: 'Nosy Be',
        region: 'Diana',
        latitude: -13.4420,
        longitude: 48.2420,
        phone: '+261 32 04 555 66',
        coverImage: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
        rating: 4.5,
        reviewCount: 178,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'La Table d\'Alexandre - Restaurant Gastronomique Nosy Be',
        metaDescription: 'Fusion franco-malgache à Nosy Be. Vanille locale, zébu flambé, cuisine raffinée.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['français', 'malgache', 'fusion']),
          priceRange: 'UPSCALE' as const,
          openingHours: JSON.stringify({ mardi: { open: '11:30', close: '14:30' }, mercredi: { open: '11:30', close: '14:30' }, jeudi: { open: '11:30', close: '22:00' }, vendredi: { open: '11:30', close: '22:00' }, samedi: { open: '11:30', close: '22:00' }, dimanche: { open: '11:30', close: '14:30' } }),
          hasReservation: true, hasWifi: true,
          specialties: JSON.stringify(['Plats à la vanille Nosy Be', 'Zébu flambé', 'Desserts créatifs']),
          avgMainCourse: 55000, avgBeer: 10000,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Phare',
        slug: 'le-phare-nosy-be',
        description: "Lounge-bar avec vue sur le port de Hell-Ville. Cocktails créatifs, tartare de thon, ambiance sunset. L'endroit idéal pour un apéritif face à la mer avec DJ sets le week-end.",
        shortDescription: 'Lounge-bar vue port, cocktails sunset à Hell-Ville',
        address: 'Hell-Ville (Andoany)',
        city: 'Nosy Be',
        district: 'Hell-Ville',
        region: 'Diana',
        latitude: -13.4040,
        longitude: 48.2680,
        phone: '+261 32 05 612 22',
        coverImage: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
        rating: 4.0,
        reviewCount: 112,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Phare - Lounge Bar Nosy Be',
        metaDescription: 'Lounge-bar face au port de Hell-Ville. Cocktails, tartare de thon, sunset.',
        restaurant: {
          category: 'LOUNGE' as const,
          cuisineTypes: JSON.stringify(['cocktails', 'fruits de mer', 'tapas']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '17:00', close: '23:00' }, mardi: { open: '17:00', close: '23:00' }, mercredi: { open: '17:00', close: '23:00' }, jeudi: { open: '17:00', close: '23:00' }, vendredi: { open: '17:00', close: '01:00' }, samedi: { open: '17:00', close: '01:00' }, dimanche: { open: '17:00', close: '23:00' } }),
          hasWifi: true,
          specialties: JSON.stringify(['Cocktail Ylang-Ylang', 'Tartare de thon', 'Sunset tapas']),
          avgMainCourse: 35000, avgBeer: 10000,
        },
      },
      // NOSY BE - HOTELS
      {
        type: 'HOTEL' as const,
        name: 'Constance Tsarabanjina',
        slug: 'constance-tsarabanjina-nosy-be',
        description: "Resort 5 étoiles sur une île privée de l'archipel de Nosy Be. 25 bungalows pieds dans l'eau, plages immaculées, snorkeling exceptionnel. All-inclusive possible. L'un des hôtels les plus exclusifs de Madagascar.",
        shortDescription: 'Île privée 5 étoiles, bungalows pieds dans l\'eau, snorkeling',
        address: 'Île Tsarabanjina, Archipel Nosy Be',
        city: 'Nosy Be',
        region: 'Diana',
        latitude: -13.2840,
        longitude: 48.0510,
        phone: '+261 20 86 613 01',
        coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        rating: 4.5,
        reviewCount: 156,
        isFeatured: true,
        isPremium: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-Constance_Tsarabanjina',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Constance Tsarabanjina - Île Privée 5 Étoiles',
        metaDescription: 'Resort 5 étoiles sur île privée. Bungalows pieds dans l\'eau, snorkeling, all-inclusive. Nosy Be.',
        hotel: {
          starRating: 5, hotelType: 'resort',
          amenities: JSON.stringify(['wifi', 'generator', 'restaurant', 'spa', 'bar', 'plage_privee', 'plongee', 'kayak']),
          checkInTime: '12:00', checkOutTime: '10:00',
          roomTypes: [
            { name: 'Beach Villa', capacity: 2, pricePerNight: 900000, amenities: JSON.stringify(['vue_mer', 'terrasse', 'douche_exterieure']) },
            { name: 'Beach Villa Premium', capacity: 3, pricePerNight: 1500000, amenities: JSON.stringify(['vue_mer', 'terrasse', 'piscine_privee']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Vanila Hotel & Spa',
        slug: 'vanila-hotel-spa-nosy-be',
        description: "Boutique hôtel 4 étoiles en bord de mer à Ambaro Bay. Spa primé, piscine à débordement, restaurant gastronomique et jardins tropicaux luxuriants. Ambiance zen et raffinée.",
        shortDescription: 'Boutique hôtel 4 étoiles, spa primé, piscine à débordement',
        address: 'Ambaro Bay',
        city: 'Nosy Be',
        region: 'Diana',
        latitude: -13.3700,
        longitude: 48.2150,
        phone: '+261 20 86 920 02',
        coverImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        rating: 4.5,
        reviewCount: 234,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Vanila Hotel & Spa - Boutique Hôtel Nosy Be',
        metaDescription: 'Boutique hôtel 4 étoiles à Nosy Be. Spa primé, piscine à débordement, restaurant gastronomique.',
        hotel: {
          starRating: 4, hotelType: 'boutique',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'bar', 'plage']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Jardin', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'vue_jardin']) },
            { name: 'Suite Mer', capacity: 2, pricePerNight: 550000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'minibar', 'vue_mer', 'terrasse']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Ravintsara Wellness Hotel',
        slug: 'ravintsara-wellness-nosy-be',
        description: "Hôtel wellness perché sur les hauteurs d'Ambondrona avec vue panoramique sur l'océan. Yoga, huiles essentielles d'ylang-ylang local, restaurant bio. Concept bien-être unique à Madagascar.",
        shortDescription: 'Hôtel wellness, yoga et huiles essentielles ylang-ylang, vue océan',
        address: 'Ambondrona',
        city: 'Nosy Be',
        region: 'Diana',
        latitude: -13.3980,
        longitude: 48.2280,
        phone: '+261 32 11 555 00',
        coverImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800',
        rating: 4.5,
        reviewCount: 145,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Ravintsara Wellness Hotel - Bien-être à Nosy Be',
        metaDescription: 'Hôtel wellness à Nosy Be. Yoga, spa ylang-ylang, restaurant bio, vue océan.',
        hotel: {
          starRating: 4, hotelType: 'wellness',
          amenities: JSON.stringify(['wifi', 'generator', 'pool', 'restaurant', 'spa', 'yoga', 'ac', 'bar']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Zen', capacity: 2, pricePerNight: 300000, amenities: JSON.stringify(['wifi', 'ac', 'vue_ocean']) },
            { name: 'Villa Wellness', capacity: 2, pricePerNight: 650000, amenities: JSON.stringify(['wifi', 'ac', 'piscine_privee', 'terrasse']) },
          ],
        },
      },
      // =============================================
      // SAINTE-MARIE
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Princesse Bora Lodge & Spa',
        slug: 'princesse-bora-sainte-marie',
        description: "Lodge 4 étoiles en bord de mer à Sainte-Marie. Bungalows face à l'océan, spa complet, excursions baleines (juillet-septembre), piscine à débordement. Restaurant avec cuisine franco-malgache de qualité.",
        shortDescription: 'Lodge 4 étoiles face à l\'océan, excursions baleines, spa',
        address: 'Ambodifotatra',
        city: 'Sainte-Marie',
        region: 'Analanjirofo',
        latitude: -16.8495,
        longitude: 49.9215,
        phone: '+261 20 57 912 18',
        coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
        rating: 4.5,
        reviewCount: 456,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Hotel_Review-g479202-d1170538-Princesse_Bora',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Princesse Bora Lodge & Spa - Sainte-Marie Madagascar',
        metaDescription: 'Lodge 4 étoiles à Sainte-Marie. Bungalows face océan, baleines, spa, piscine à débordement.',
        hotel: {
          starRating: 4, hotelType: 'lodge',
          amenities: JSON.stringify(['wifi', 'generator', 'pool', 'restaurant', 'spa', 'ac', 'bar', 'plage', 'excursions_baleines']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Bungalow Jardin', capacity: 2, pricePerNight: 400000, amenities: JSON.stringify(['wifi', 'ac', 'terrasse']) },
            { name: 'Bungalow Mer', capacity: 2, pricePerNight: 700000, amenities: JSON.stringify(['wifi', 'ac', 'vue_mer', 'terrasse']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Boraha Village',
        slug: 'boraha-village-sainte-marie',
        description: "Hôtel 3 étoiles avec bungalows sur pilotis au-dessus de l'eau, accès direct plage, centre de plongée sur place. Restaurant spécialisé fruits de mer et cuisine créole.",
        shortDescription: 'Bungalows sur pilotis, plongée et plage à Sainte-Marie',
        address: 'Anse Ambodiatafana',
        city: 'Sainte-Marie',
        region: 'Analanjirofo',
        latitude: -16.8660,
        longitude: 49.9370,
        phone: '+261 34 05 614 05',
        coverImage: 'https://images.unsplash.com/photo-1499793983394-12042d5ee400?w=800',
        rating: 4.5,
        reviewCount: 289,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Boraha Village - Bungalows sur Pilotis Sainte-Marie',
        metaDescription: 'Bungalows sur pilotis à Sainte-Marie. Plongée, plage, cuisine créole.',
        hotel: {
          starRating: 3, hotelType: 'resort',
          amenities: JSON.stringify(['wifi', 'generator', 'restaurant', 'bar', 'plage', 'plongee']),
          checkInTime: '13:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Bungalow Pilotis', capacity: 2, pricePerNight: 300000, amenities: JSON.stringify(['wifi', 'vue_mer']) },
            { name: 'Bungalow Plage', capacity: 2, pricePerNight: 200000, amenities: JSON.stringify(['wifi', 'terrasse']) },
          ],
        },
      },
      // =============================================
      // TULEAR / IFATY / ANAKAO
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Chez Alain',
        slug: 'chez-alain-toliara',
        description: "Restaurant de plage mythique de Tuléar, Chez Alain sert des fruits de mer grillés les pieds dans le sable. Langouste, crevettes, poisson du jour à prix abordables. Ambiance décontractée face au Canal du Mozambique.",
        shortDescription: 'Fruits de mer grillés pieds dans le sable à Tuléar',
        address: 'Plage de la Batterie, Boulevard Lyautey',
        city: 'Toliara',
        region: 'Atsimo-Andrefana',
        latitude: -23.3545,
        longitude: 43.6710,
        phone: '+261 34 07 525 25',
        coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
        rating: 4.0,
        reviewCount: 187,
        dataSource: 'csv_import',
        sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g298065-Chez_Alain-Toliara',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Chez Alain - Fruits de Mer à Tuléar',
        metaDescription: 'Restaurant de plage à Tuléar. Langouste grillée, crevettes, pieds dans le sable face au canal du Mozambique.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['fruits de mer', 'malgache', 'grillades']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '10:00', close: '21:00' }, mardi: { open: '10:00', close: '21:00' }, mercredi: { open: '10:00', close: '21:00' }, jeudi: { open: '10:00', close: '21:00' }, vendredi: { open: '10:00', close: '22:00' }, samedi: { open: '10:00', close: '22:00' }, dimanche: { open: '10:00', close: '21:00' } }),
          hasParking: true,
          specialties: JSON.stringify(['Langouste grillée', 'Crevettes géantes', 'Poisson du jour']),
          avgMainCourse: 30000, avgBeer: 6000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Paradisier',
        slug: 'le-paradisier-ifaty',
        description: "Écolodge de charme à Ifaty avec bungalows dans un jardin de baobabs. Piscine à débordement face au Canal du Mozambique, restaurant gastronomique franco-malgache, excursions baleines et récif corallien.",
        shortDescription: 'Écolodge de charme dans un jardin de baobabs, piscine vue mer',
        address: 'Mangily-Ifaty',
        city: 'Ifaty',
        region: 'Atsimo-Andrefana',
        latitude: -23.1530,
        longitude: 43.6120,
        phone: '+261 32 04 393 85',
        coverImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
        rating: 4.5,
        reviewCount: 198,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Paradisier - Écolodge à Ifaty Madagascar',
        metaDescription: 'Écolodge à Ifaty. Bungalows dans jardin de baobabs, piscine vue mer, gastronomie.',
        hotel: {
          starRating: 4, hotelType: 'ecolodge',
          amenities: JSON.stringify(['wifi', 'generator', 'pool', 'restaurant', 'bar', 'plage', 'excursions']),
          checkInTime: '13:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Bungalow Jardin', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['ventilateur', 'terrasse']) },
            { name: 'Bungalow Vue Mer', capacity: 2, pricePerNight: 450000, amenities: JSON.stringify(['ac', 'vue_mer', 'terrasse']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Salary Bay',
        slug: 'salary-bay-madagascar',
        description: "Lodge de luxe isolé accessible uniquement par bateau, entre Ifaty et Anakao. Plage privée immaculée, snorkeling et plongée exceptionnels, cuisine gastronomique avec langouste au menu quotidien. Éco-tourisme de luxe.",
        shortDescription: 'Lodge de luxe isolé, plage privée, accessible par bateau',
        address: 'Baie de Salary',
        city: 'Salary',
        region: 'Atsimo-Andrefana',
        latitude: -23.3700,
        longitude: 43.5350,
        phone: '+261 34 20 200 20',
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        rating: 4.5,
        reviewCount: 167,
        isPremium: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Salary Bay - Lodge de Luxe Isolé Madagascar',
        metaDescription: 'Lodge de luxe accessible par bateau. Plage privée, snorkeling, langouste quotidienne.',
        hotel: {
          starRating: 4, hotelType: 'lodge',
          amenities: JSON.stringify(['generator', 'restaurant', 'bar', 'plage_privee', 'plongee', 'kayak', 'excursions']),
          checkInTime: '12:00', checkOutTime: '10:00',
          roomTypes: [
            { name: 'Bungalow Standard', capacity: 2, pricePerNight: 500000, amenities: JSON.stringify(['vue_mer', 'terrasse']) },
            { name: 'Bungalow Luxe', capacity: 2, pricePerNight: 900000, amenities: JSON.stringify(['vue_mer', 'terrasse', 'salon']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Anakao Ocean Lodge',
        slug: 'anakao-ocean-lodge',
        description: "Lodge 4 étoiles face à la mer à Anakao. Bungalows de luxe, excursions vers Nosy Ve (oiseaux tropicaux), snorkeling sur récif corallien, restaurant gastronomique en pension complète. Pirogue traditionnelle Vezo.",
        shortDescription: 'Lodge 4 étoiles face à la mer, excursions Nosy Ve, snorkeling',
        address: 'Anakao',
        city: 'Anakao',
        region: 'Atsimo-Andrefana',
        latitude: -23.6720,
        longitude: 43.4950,
        phone: '+261 20 22 540 34',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        rating: 4.0,
        reviewCount: 278,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Anakao Ocean Lodge - Lodge 4 Étoiles Anakao',
        metaDescription: 'Lodge face à la mer à Anakao. Excursions Nosy Ve, snorkeling, pirogue Vezo.',
        hotel: {
          starRating: 4, hotelType: 'lodge',
          amenities: JSON.stringify(['generator', 'restaurant', 'bar', 'plage', 'plongee', 'excursions', 'pirogue']),
          checkInTime: '12:00', checkOutTime: '10:00',
          roomTypes: [
            { name: 'Bungalow Plage', capacity: 2, pricePerNight: 400000, amenities: JSON.stringify(['vue_mer', 'terrasse']) },
            { name: 'Suite Ocean', capacity: 3, pricePerNight: 750000, amenities: JSON.stringify(['vue_mer', 'terrasse', 'salon']) },
          ],
        },
      },
      // =============================================
      // DIEGO SUAREZ
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Libertalia',
        slug: 'le-libertalia-diego-suarez',
        description: "Restaurant de fruits de mer haut de gamme sur la Rue Colbert à Diego Suarez. Langouste, camarons géants, poisson frais du jour. Ambiance coloniale française, service soigné. Populaire auprès des expatriés et voyageurs.",
        shortDescription: 'Fruits de mer haut de gamme, Rue Colbert à Diego Suarez',
        address: 'Rue Colbert',
        city: 'Diego Suarez',
        region: 'Diana',
        latitude: -12.2770,
        longitude: 49.2920,
        phone: '+261 32 40 621 88',
        coverImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
        rating: 4.0,
        reviewCount: 156,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Le Libertalia - Restaurant Diego Suarez',
        metaDescription: 'Fruits de mer haut de gamme à Diego Suarez. Langouste, camarons, ambiance coloniale.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['fruits de mer', 'français', 'malgache']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '11:30', close: '22:00' }, mardi: { open: '11:30', close: '22:00' }, mercredi: { open: '11:30', close: '22:00' }, jeudi: { open: '11:30', close: '22:00' }, vendredi: { open: '11:30', close: '22:30' }, samedi: { open: '11:30', close: '22:30' }, dimanche: { open: '11:30', close: '14:30' } }),
          hasReservation: true, hasWifi: true, hasParking: true,
          specialties: JSON.stringify(['Langouste', 'Camarons géants', 'Poisson du jour']),
          avgMainCourse: 35000, avgBeer: 7000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Allamanda Hotel',
        slug: 'allamanda-hotel-diego-suarez',
        description: "Hôtel moderne avec piscine et vue mer vers Nosy Lonja (Pain de Sucre). Excellent restaurant sur place, proche des excursions vers Ramena et la Mer d'Émeraude. Meilleur rapport qualité-prix de Diego.",
        shortDescription: 'Hôtel moderne, piscine, vue sur le Pain de Sucre',
        address: 'Route de Ramena',
        city: 'Diego Suarez',
        region: 'Diana',
        latitude: -12.2630,
        longitude: 49.3050,
        phone: '+261 20 82 229 59',
        coverImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
        rating: 4.5,
        reviewCount: 198,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Allamanda Hotel - Diego Suarez Madagascar',
        metaDescription: 'Hôtel moderne à Diego Suarez. Piscine, vue Pain de Sucre, restaurant, excursions.',
        hotel: {
          starRating: 3, hotelType: 'hotel',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'ac', 'tv', 'bar']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 180000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Chambre Vue Mer', capacity: 2, pricePerNight: 320000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'vue_mer', 'balcon']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Nature Lodge',
        slug: 'nature-lodge-diego-suarez',
        description: "Écolodge perché sur une colline avec vue panoramique sur la baie de Diego Suarez. Bungalows en matériaux naturels, piscine, excursions Tsingy Rouge et Mer d'Émeraude organisées. Cadre exceptionnel.",
        shortDescription: 'Écolodge vue panoramique baie de Diego, excursions Tsingy Rouge',
        address: 'Route de Ramena',
        city: 'Diego Suarez',
        region: 'Diana',
        latitude: -12.2540,
        longitude: 49.3220,
        phone: '+261 32 11 865 00',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800',
        rating: 4.5,
        reviewCount: 167,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Nature Lodge - Écolodge Diego Suarez',
        metaDescription: 'Écolodge vue baie de Diego. Bungalows naturels, piscine, excursions Tsingy Rouge.',
        hotel: {
          starRating: 3, hotelType: 'ecolodge',
          amenities: JSON.stringify(['wifi', 'generator', 'pool', 'restaurant', 'bar', 'excursions', 'vue_panoramique']),
          checkInTime: '13:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Bungalow Nature', capacity: 2, pricePerNight: 200000, amenities: JSON.stringify(['vue_baie', 'terrasse']) },
            { name: 'Bungalow Premium', capacity: 2, pricePerNight: 350000, amenities: JSON.stringify(['vue_baie', 'terrasse', 'ac']) },
          ],
        },
      },
      // =============================================
      // ANTSIRABE
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Restaurant Zandina',
        slug: 'restaurant-zandina-antsirabe',
        description: "Cuisine fusion franco-malgache raffinée à Antsirabe. Poisson frais du lac, confit de canard, carte des vins régionaux. Considéré comme la meilleure table de la ville thermale.",
        shortDescription: 'Meilleure table d\'Antsirabe, fusion franco-malgache',
        address: 'Avenue de l\'Indépendance',
        city: 'Antsirabe',
        region: 'Vakinankaratra',
        latitude: -19.8686,
        longitude: 47.0370,
        phone: '+261 33 11 332 50',
        coverImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        rating: 4.5,
        reviewCount: 134,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Restaurant Zandina - Gastronomie Antsirabe',
        metaDescription: 'Meilleure table d\'Antsirabe. Fusion franco-malgache, vins régionaux.',
        restaurant: {
          category: 'RESTAURANT' as const,
          cuisineTypes: JSON.stringify(['français', 'malgache', 'fusion']),
          priceRange: 'MODERATE' as const,
          openingHours: JSON.stringify({ lundi: { open: '12:00', close: '14:30' }, mardi: { open: '12:00', close: '14:30' }, mercredi: { open: '12:00', close: '22:00' }, jeudi: { open: '12:00', close: '22:00' }, vendredi: { open: '12:00', close: '22:00' }, samedi: { open: '12:00', close: '22:00' } }),
          hasReservation: true, hasWifi: true,
          specialties: JSON.stringify(['Poisson du lac', 'Confit de canard', 'Vins régionaux']),
          avgMainCourse: 35000, avgBeer: 7000,
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hôtel des Thermes',
        slug: 'hotel-des-thermes-antsirabe',
        description: "Hôtel historique colonial avec bains thermaux à Antsirabe. Grand jardin, architecture classique, l'hôtel le plus emblématique de la ville thermale. Sources chaudes et spa thermal.",
        shortDescription: 'Hôtel colonial historique avec bains thermaux',
        address: 'Route des Thermes',
        city: 'Antsirabe',
        region: 'Vakinankaratra',
        latitude: -19.8732,
        longitude: 47.0367,
        phone: '+261 20 44 487 61',
        coverImage: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
        rating: 4.0,
        reviewCount: 234,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Hôtel des Thermes - Hôtel Historique Antsirabe',
        metaDescription: 'Hôtel colonial historique à Antsirabe. Bains thermaux, grand jardin, architecture classique.',
        hotel: {
          starRating: 3, hotelType: 'hotel historique',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'restaurant', 'spa', 'thermes', 'jardin', 'bar']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Classique', capacity: 2, pricePerNight: 120000, amenities: JSON.stringify(['wifi', 'tv']) },
            { name: 'Suite Coloniale', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['wifi', 'tv', 'salon', 'vue_jardin']) },
          ],
        },
      },
      // =============================================
      // FIANARANTSOA
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Tsara Guest House',
        slug: 'tsara-guest-house-fianarantsoa',
        description: "Boutique guesthouse dans un bâtiment colonial restauré à Fianarantsoa. Galerie d'art, jardin, excellent petit-déjeuner. Très prisé des voyageurs indépendants. Point de départ idéal pour la route des vins.",
        shortDescription: 'Guesthouse de charme dans un bâtiment colonial restauré',
        address: 'Rue de la Paix, Ambalapaiso',
        city: 'Fianarantsoa',
        region: 'Haute Matsiatra',
        latitude: -21.4430,
        longitude: 47.0870,
        phone: '+261 20 75 508 06',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
        rating: 4.5,
        reviewCount: 178,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Tsara Guest House - Charme à Fianarantsoa',
        metaDescription: 'Guesthouse de charme à Fianarantsoa. Bâtiment colonial, galerie d\'art, route des vins.',
        hotel: {
          starRating: 3, hotelType: 'guesthouse',
          amenities: JSON.stringify(['wifi', 'generator', 'restaurant', 'jardin', 'galerie_art']),
          checkInTime: '13:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 80000, amenities: JSON.stringify(['wifi']) },
            { name: 'Chambre Supérieure', capacity: 2, pricePerNight: 150000, amenities: JSON.stringify(['wifi', 'vue_ville']) },
          ],
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'La Rizière',
        slug: 'la-riziere-fianarantsoa',
        description: "Hôtel-restaurant surplombant les rizières en terrasse de Fianarantsoa. Cuisine française raffinée avec vins locaux, chambres confortables avec vue spectaculaire. Étape incontournable de la RN7.",
        shortDescription: 'Vue rizières en terrasse, restaurant gastronomique, vins locaux',
        address: 'RN7, Fianarantsoa',
        city: 'Fianarantsoa',
        region: 'Haute Matsiatra',
        latitude: -21.4350,
        longitude: 47.0930,
        phone: '+261 20 75 513 01',
        coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
        rating: 4.5,
        reviewCount: 212,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'La Rizière - Hôtel & Restaurant Fianarantsoa',
        metaDescription: 'Hôtel-restaurant vue rizières à Fianarantsoa. Gastronomie française, vins locaux.',
        hotel: {
          starRating: 3, hotelType: 'hotel-restaurant',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'restaurant', 'bar', 'vue_riziere']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Confort', capacity: 2, pricePerNight: 100000, amenities: JSON.stringify(['wifi', 'vue_riziere']) },
            { name: 'Chambre Supérieure', capacity: 2, pricePerNight: 180000, amenities: JSON.stringify(['wifi', 'vue_riziere', 'balcon']) },
          ],
        },
      },
      // =============================================
      // MORONDAVA
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Palissandre Côte Ouest',
        slug: 'palissandre-cote-ouest-morondava',
        description: "Resort 4 étoiles en bord de mer à Morondava, porte d'entrée vers l'Allée des Baobabs et les Tsingy. Piscine, spa, plage directe, restaurant gastronomique. Le meilleur hôtel de la région.",
        shortDescription: 'Resort 4 étoiles bord de mer, porte des Baobabs et Tsingy',
        address: 'Boulevard de Morondava',
        city: 'Morondava',
        region: 'Menabe',
        latitude: -20.2884,
        longitude: 44.2815,
        phone: '+261 20 95 523 78',
        coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        rating: 4.5,
        reviewCount: 234,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Palissandre Côte Ouest - Resort 4 Étoiles Morondava',
        metaDescription: 'Resort 4 étoiles à Morondava. Piscine, spa, plage, porte des Baobabs et Tsingy.',
        hotel: {
          starRating: 4, hotelType: 'resort',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'spa', 'ac', 'tv', 'bar', 'plage']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 250000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Suite Baobab', capacity: 2, pricePerNight: 500000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'vue_mer', 'terrasse']) },
          ],
        },
      },
      // =============================================
      // FORT DAUPHIN
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Talinjoo Hotel',
        slug: 'talinjoo-hotel-fort-dauphin',
        description: "Perché sur les falaises surplombant la plage de Libanona, le Talinjoo offre des vues spectaculaires sur l'océan. Chambres modernes, piscine, restaurant avec fruits de mer frais. Le meilleur hôtel de Fort Dauphin.",
        shortDescription: 'Sur les falaises de Libanona, vue océan spectaculaire',
        address: 'Libanona Beach',
        city: 'Fort Dauphin',
        region: 'Anosy',
        latitude: -25.0380,
        longitude: 46.9930,
        phone: '+261 20 92 212 56',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
        rating: 4.5,
        reviewCount: 189,
        isFeatured: true,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Talinjoo Hotel - Vue Océan Fort Dauphin',
        metaDescription: 'Hôtel sur les falaises de Libanona, Fort Dauphin. Vue océan, piscine, fruits de mer.',
        hotel: {
          starRating: 3, hotelType: 'hotel',
          amenities: JSON.stringify(['wifi', 'generator', 'parking', 'pool', 'restaurant', 'ac', 'tv', 'bar', 'vue_ocean']),
          checkInTime: '14:00', checkOutTime: '11:00',
          roomTypes: [
            { name: 'Chambre Standard', capacity: 2, pricePerNight: 200000, amenities: JSON.stringify(['wifi', 'ac', 'tv']) },
            { name: 'Chambre Vue Océan', capacity: 2, pricePerNight: 350000, amenities: JSON.stringify(['wifi', 'ac', 'tv', 'vue_ocean', 'balcon']) },
          ],
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Chez Jacqueline',
        slug: 'chez-jacqueline-fort-dauphin',
        description: "Gargote authentique au cœur de Fort Dauphin, Chez Jacqueline sert de la langouste fraîche à prix imbattable, du curry de crabe et du poisson grillé. Cuisine malgache sans chichis, ambiance locale chaleureuse.",
        shortDescription: 'Gargote authentique, langouste à prix locaux, Fort Dauphin',
        address: 'Centre Ville',
        city: 'Fort Dauphin',
        region: 'Anosy',
        latitude: -25.0320,
        longitude: 47.0000,
        phone: '+261 34 12 500 33',
        coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        rating: 4.0,
        reviewCount: 98,
        dataSource: 'csv_import',
        sourceAttribution: 'TripAdvisor',
        moderationStatus: 'pending_review',
        metaTitle: 'Chez Jacqueline - Gargote Fort Dauphin',
        metaDescription: 'Gargote authentique à Fort Dauphin. Langouste fraîche pas chère, curry de crabe.',
        restaurant: {
          category: 'GARGOTE' as const,
          cuisineTypes: JSON.stringify(['malgache', 'fruits de mer']),
          priceRange: 'BUDGET' as const,
          openingHours: JSON.stringify({ lundi: { open: '07:00', close: '15:00' }, mardi: { open: '07:00', close: '15:00' }, mercredi: { open: '07:00', close: '15:00' }, jeudi: { open: '07:00', close: '15:00' }, vendredi: { open: '07:00', close: '15:00' }, samedi: { open: '07:00', close: '14:00' } }),
          hasTakeaway: true,
          specialties: JSON.stringify(['Langouste fraîche', 'Curry de crabe', 'Poisson grillé']),
          avgMainCourse: 15000, avgBeer: 4000,
        },
      },
    ];

    // =============================================
    // INSERT ALL
    // =============================================
    for (const item of establishments) {
      // Check if slug already exists
      const existing = await prisma.establishment.findUnique({ where: { slug: item.slug } });
      if (existing) {
        created.skipped++;
        continue;
      }

      const { type, restaurant, hotel, ...estData } = item as any;

      if (type === 'RESTAURANT' && restaurant) {
        await prisma.establishment.create({
          data: { type, ...estData, restaurant: { create: restaurant } },
        });
        created.restaurants++;
      } else if (type === 'HOTEL' && hotel) {
        const { roomTypes, ...hotelFields } = hotel;
        await prisma.establishment.create({
          data: {
            type, ...estData,
            hotel: { create: { ...hotelFields, roomTypes: roomTypes ? { create: roomTypes } : undefined } },
          },
        });
        created.hotels++;
      } else if (type === 'ATTRACTION') {
        const { attraction, ...rest } = item as any;
        await prisma.establishment.create({
          data: { type, ...rest, attraction: { create: attraction } },
        });
        created.attractions++;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Sourcing terminé ! ${created.restaurants} restaurants, ${created.hotels} hôtels, ${created.attractions} attractions importés. ${created.skipped} doublons ignorés.`,
      created,
      note: 'Tous les établissements sont en statut "pending_review" pour modération admin.',
    });
  } catch (error: unknown) {
    logger.error('Sourcing error:', error);
    const message = error instanceof Error ? error.message : 'Erreur inconnue';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
