import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

import { logger } from '@/lib/logger';
// Seed Petit Futé - Établissements de qualité sourcés depuis Petit Futé Madagascar & TripAdvisor
// Focus: Coup de Coeur Petit Futé + établissements très bien notés
// Tous en statut "pending_review" pour modération admin

export async function POST() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Non autorisé en production' }, { status: 403 });
  }

  try {
    let created = { restaurants: 0, hotels: 0, skipped: 0 };

    const establishments = [
      // =============================================
      // ANTANANARIVO - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'La Varangue',
        slug: 'la-varangue-antananarivo',
        description: "Restaurant gastronomique emblématique d'Antananarivo dans un bâtiment colonial magnifiquement restauré. Véranda avec vue panoramique sur la ville. Cuisine française raffinée fusionnée avec les meilleurs ingrédients malgaches. Service impeccable, ambiance romantique. Coup de Cœur Petit Futé.",
        shortDescription: 'Gastronomique colonial, vue panoramique, Coup de Cœur Petit Futé',
        address: '17 Rue Rainitovo, Antaninarenina',
        city: 'Antananarivo',
        district: 'Haute-Ville',
        region: 'Analamanga',
        latitude: -18.9150,
        longitude: 47.5280,
        phone: '+261 20 22 227 06',
        website: 'https://www.hotel-restaurant-lavarangue.com',
        coverImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
        rating: 4.5,
        reviewCount: 420,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/1834962-restaurant-la-varangue.html',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'malgache fusion'],
          priceRange: 'LUXURY',
          avgMainCourse: 75000,
          avgBeer: 12000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
          hasParking: false,
          openingHours: {
            monday: 'Fermé',
            tuesday: { open: '12:00', close: '14:00' },
            wednesday: { open: '12:00', close: '14:00' },
            thursday: { open: '12:00', close: '14:00' },
            friday: { open: '12:00', close: '14:00' },
            saturday: { open: '12:00', close: '14:00' },
          },
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Ribaudière',
        slug: 'la-ribaudiere-antananarivo',
        description: "L'une des plus belles tables de la capitale, dans une villa coloniale entourée d'un jardin à Ambatobe. Cuisine française gastronomique avec produits malgaches de saison. Carte des vins exceptionnelle. Ambiance élégante et décontractée, idéale pour les occasions spéciales. Coup de Cœur Petit Futé.",
        shortDescription: 'Gastronomique en villa coloniale, jardin, cave à vins',
        address: 'Lot IVN 99, Ambatobe',
        city: 'Antananarivo',
        district: 'Ambatobe',
        region: 'Analamanga',
        latitude: -18.8980,
        longitude: 47.5420,
        phone: '+261 20 22 425 76',
        coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=800&q=80',
        rating: 4.5,
        reviewCount: 280,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique'],
          priceRange: 'LUXURY',
          avgMainCourse: 80000,
          avgBeer: 12000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Boussole',
        slug: 'la-boussole-antananarivo',
        description: "Bistrot français prisé par la communauté expatriée à Isoraka. Cuisine française traditionnelle de qualité, réputé pour ses excellents steaks et canard. Intérieur en bois chaleureux, service attentionné. Ambiance conviviale et authentique.",
        shortDescription: 'Bistrot français, steaks et canard, ambiance conviviale',
        address: 'Rue Rainizanabololona, Isoraka',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9120,
        longitude: 47.5250,
        phone: '+261 20 22 264 13',
        coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        rating: 4.5,
        reviewCount: 310,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'bistrot'],
          priceRange: 'MODERATE',
          avgMainCourse: 45000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Nerone Ristorante',
        slug: 'nerone-ristorante-antananarivo',
        description: "Restaurant italien haut de gamme à Ivandry, très prisé par la communauté d'affaires et les résidents italiens. Cuisine italienne authentique par un chef italien, pâtes fraîches maison, risottos et sélection impressionnante de vins italiens. Décor moderne et élégant.",
        shortDescription: 'Italien haut de gamme, chef italien, pâtes maison',
        address: 'Ivandry, Galaxy Andraharo',
        city: 'Antananarivo',
        district: 'Ivandry',
        region: 'Analamanga',
        latitude: -18.8950,
        longitude: 47.5350,
        phone: '+261 20 22 439 15',
        coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        rating: 4.5,
        reviewCount: 245,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'pizza', 'pasta'],
          priceRange: 'MODERATE',
          avgMainCourse: 50000,
          avgBeer: 12000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Chez Mariette',
        slug: 'chez-mariette-antananarivo',
        description: "Expérience malgache authentique à Isoraka. Mariette prépare quotidiennement des plats traditionnels selon le marché : romazava, ravitoto, hen'omby ritra. Cadre simple et familial, portions généreuses. Extrêmement populaire auprès des locaux et voyageurs cherchant les vraies saveurs malgaches.",
        shortDescription: 'Cuisine malgache authentique, plats du marché quotidiens',
        address: 'Rue Rabezavana, Isoraka',
        city: 'Antananarivo',
        district: 'Isoraka',
        region: 'Analamanga',
        latitude: -18.9130,
        longitude: 47.5240,
        phone: '+261 20 22 359 46',
        coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
        rating: 4.0,
        reviewCount: 180,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'GARGOTE',
          cuisineTypes: ['malgache', 'traditionnel'],
          priceRange: 'BUDGET',
          avgMainCourse: 15000,
          avgBeer: 5000,
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: false,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'La Table d\'Hôte',
        slug: 'la-table-dhote-antananarivo',
        description: "Restaurant français intime caché dans la Haute-Ville. Menu limité mais raffiné qui change régulièrement selon les produits de saison. Ancienne maison de Tana avec seulement quelques tables, créant une atmosphère exclusive. Réservation indispensable.",
        shortDescription: 'Français intime, menu saisonnier, Haute-Ville',
        address: 'Rue Ambondrona, Haute-Ville',
        city: 'Antananarivo',
        district: 'Haute-Ville',
        region: 'Analamanga',
        latitude: -18.9170,
        longitude: 47.5290,
        phone: '+261 20 22 660 48',
        coverImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
        rating: 4.5,
        reviewCount: 156,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'créatif'],
          priceRange: 'MODERATE',
          avgMainCourse: 55000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Toko Telo',
        slug: 'toko-telo-antananarivo',
        description: "Café-restaurant et espace culturel branché dans la Haute-Ville. Cuisine malgache créative avec présentation moderne. Galerie d'art et espace événementiel. Populaire auprès d'une clientèle jeune et créative. Excellent café et gâteaux maison.",
        shortDescription: 'Café culturel créatif, cuisine malgache revisitée',
        address: 'Rue Ratsimilaho, Haute-Ville',
        city: 'Antananarivo',
        district: 'Haute-Ville',
        region: 'Analamanga',
        latitude: -18.9165,
        longitude: 47.5285,
        phone: '+261 34 49 000 49',
        coverImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80',
        rating: 4.5,
        reviewCount: 200,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'CAFE',
          cuisineTypes: ['malgache', 'créatif', 'café'],
          priceRange: 'BUDGET',
          avgMainCourse: 22000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Chocolaterie Robert',
        slug: 'chocolaterie-robert-antananarivo',
        description: "Salon de thé et boutique du chocolatier malgache le plus célèbre (depuis 1940). Chocolat chaud, pâtisseries au chocolat, gâteaux et repas légers. Expérience unique pour déguster l'un des meilleurs chocolats mono-origine au monde. Vente de tablettes et cadeaux.",
        shortDescription: 'Chocolatier iconique depuis 1940, salon de thé',
        address: 'Avenue de l\'Indépendance, Analakely',
        city: 'Antananarivo',
        district: 'Analakely',
        region: 'Analamanga',
        latitude: -18.9100,
        longitude: 47.5230,
        phone: '+261 20 22 205 47',
        website: 'https://www.chocolatrobert.com',
        coverImage: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&q=80',
        rating: 4.0,
        reviewCount: 350,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57588-antananarivo/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'CAFE',
          cuisineTypes: ['pâtisserie', 'chocolaterie', 'salon de thé'],
          priceRange: 'BUDGET',
          avgMainCourse: 12000,
          avgBeer: null,
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: false,
        },
      },

      // =============================================
      // NOSY BE - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'La Table d\'Alexandre',
        slug: 'la-table-dalexandre-nosy-be',
        description: "La plus belle table de Nosy Be. Cuisine gastronomique française avec influences malgaches, produits frais locaux et fruits de mer du jour. Terrasse élégante avec vue sur mer. Chef utilisant des ingrédients de saison. Coup de Cœur Petit Futé, régulièrement primé.",
        shortDescription: 'Gastronomique vue mer, meilleur restaurant de Nosy Be',
        address: 'Ambondrona, Hotel Vanila',
        city: 'Nosy Be',
        district: 'Ambondrona',
        region: 'Diana',
        latitude: -13.3500,
        longitude: 48.2700,
        phone: '+261 32 07 048 00',
        coverImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
        rating: 4.5,
        reviewCount: 380,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/d1475-nosy-be/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fruits de mer'],
          priceRange: 'LUXURY',
          avgMainCourse: 70000,
          avgBeer: 12000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Karibo Restaurant',
        slug: 'karibo-restaurant-nosy-be',
        description: "Restaurant de plage tendance sur la plage de Madirokely. Pizza au feu de bois et fruits de mer. Cadre idyllique en bord de mer, parfait pour un dîner au coucher du soleil. Populaire auprès des jeunes touristes.",
        shortDescription: 'Plage, pizza au feu de bois et fruits de mer',
        address: 'Plage de Madirokely',
        city: 'Nosy Be',
        district: 'Madirokely',
        region: 'Diana',
        latitude: -13.3600,
        longitude: 48.2600,
        phone: '+261 34 14 000 14',
        coverImage: 'https://images.unsplash.com/photo-1528698827591-e19cef791f48?w=800&q=80',
        rating: 4.0,
        reviewCount: 250,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/d1475-nosy-be/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'fruits de mer', 'pizza'],
          priceRange: 'MODERATE',
          avgMainCourse: 30000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: true,
          hasReservation: false,
          hasWifi: true,
        },
      },

      // =============================================
      // MAJUNGA - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Quai Ouest',
        slug: 'le-quai-ouest-mahajanga',
        description: "Le meilleur restaurant de Majunga. Emplacement exceptionnel sur la corniche face au Canal du Mozambique. Cuisine gastronomique française avec fruits de mer frais. Salle ouverte design face à l'océan, carte des vins excellente. Coup de Cœur Petit Futé.",
        shortDescription: 'Gastronomique vue mer, meilleur de Majunga, Coup de Cœur',
        address: 'Boulevard Marcoz, Corniche',
        city: 'Mahajanga',
        district: 'Corniche',
        region: 'Boeny',
        latitude: -15.7150,
        longitude: 46.3200,
        phone: '+261 32 07 621 00',
        coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
        rating: 4.5,
        reviewCount: 320,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57610-majunga-mahajanga/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fruits de mer'],
          priceRange: 'MODERATE',
          avgMainCourse: 50000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Le Barracuda',
        slug: 'le-barracuda-mahajanga',
        description: "Restaurant de fruits de mer populaire sur la corniche avec vues spectaculaires au coucher du soleil. Poisson grillé frais, calamars, crabe. Ambiance décontractée pieds dans le sable. Cuisine simple mais excellente.",
        shortDescription: 'Fruits de mer grillés face à l\'océan, coucher de soleil',
        address: 'Boulevard Poincaré, Corniche',
        city: 'Mahajanga',
        district: 'Corniche',
        region: 'Boeny',
        latitude: -15.7160,
        longitude: 46.3180,
        phone: '+261 34 07 622 22',
        coverImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
        rating: 4.0,
        reviewCount: 190,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57610-majunga-mahajanga/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['fruits de mer', 'grillades', 'malgache'],
          priceRange: 'MODERATE',
          avgMainCourse: 25000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: false,
          hasWifi: false,
        },
      },

      // =============================================
      // DIEGO SUAREZ - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Libertalia',
        slug: 'le-libertalia-diego-suarez',
        description: "Restaurant phare de Diego Suarez, nommé d'après la légendaire république pirate. Cuisine française fine dining avec des fruits de mer exceptionnels : homard thermidor et gratin de crabe légendaires. Décor colonial élégant avec véranda. Cave à vins excellente. N°1 de Diego sur TripAdvisor. Coup de Cœur Petit Futé.",
        shortDescription: 'Fine dining, fruits de mer exceptionnels, N°1 de Diego',
        address: 'Rue Colbert, Centre-ville',
        city: 'Diego Suarez',
        district: 'Centre-ville',
        region: 'Diana',
        latitude: -12.2720,
        longitude: 49.2935,
        phone: '+261 32 07 119 00',
        coverImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
        rating: 4.5,
        reviewCount: 450,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57985-diego-suarez-antsiranana/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fruits de mer'],
          priceRange: 'MODERATE',
          avgMainCourse: 55000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },

      // =============================================
      // SAINTE-MARIE - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Idylle Beach',
        slug: 'idylle-beach-sainte-marie',
        description: "Destination gastronomique phare de Sainte-Marie. Restaurant de plage romantique, pieds dans le sable sous les cocotiers. Cuisine française gastronomique avec homard, crevettes et poissons frais. Observation des baleines depuis la plage en saison (juillet-septembre). Coup de Cœur Petit Futé.",
        shortDescription: 'Gastronomique plage, homard, observation des baleines',
        address: 'Ambodifotatra, côte sud',
        city: 'Sainte-Marie',
        district: 'Ambodifotatra',
        region: 'Analanjirofo',
        latitude: -16.8650,
        longitude: 49.9250,
        phone: '+261 32 07 538 00',
        coverImage: 'https://images.unsplash.com/photo-1528698827591-e19cef791f48?w=800&q=80',
        rating: 4.5,
        reviewCount: 280,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58023-ile-sainte-marie/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'fruits de mer', 'créole'],
          priceRange: 'MODERATE',
          avgMainCourse: 45000,
          avgBeer: 10000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },

      // =============================================
      // TULEAR - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Jardin du Sud',
        slug: 'le-jardin-du-sud-tulear',
        description: "Meilleur restaurant de Tuléar. Jardin tropical magnifique, chef français préparant des plats gastronomiques avec ingrédients locaux : foie gras, homard, filet de zébu. Atmosphère sophistiquée mais décontractée. Desserts exceptionnels. Coup de Cœur Petit Futé.",
        shortDescription: 'Gastronomique en jardin tropical, meilleur de Tuléar',
        address: 'Boulevard Lyautey, Centre-ville',
        city: 'Tuléar',
        district: 'Centre-ville',
        region: 'Atsimo-Andrefana',
        latitude: -23.3500,
        longitude: 43.6700,
        phone: '+261 32 02 440 55',
        coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=800&q=80',
        rating: 4.5,
        reviewCount: 310,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58027-tulear/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'gastronomique', 'fruits de mer'],
          priceRange: 'MODERATE',
          avgMainCourse: 45000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },
      {
        type: 'RESTAURANT' as const,
        name: 'Chez Lorenzo',
        slug: 'chez-lorenzo-ifaty',
        description: "Sur la plage d'Ifaty-Mangily, cuisine italienne et fruits de mer exceptionnels les pieds dans le sable. Poisson grillé entier, calamars, pâtes maison. Vues sur le Canal du Mozambique au coucher du soleil. Incontournable du littoral sud.",
        shortDescription: 'Italien plage, fruits de mer, coucher de soleil sur Ifaty',
        address: 'Front de mer, Mangily-Ifaty',
        city: 'Tuléar',
        district: 'Ifaty',
        region: 'Atsimo-Andrefana',
        latitude: -23.1500,
        longitude: 43.6100,
        phone: '+261 32 04 300 00',
        coverImage: 'https://images.unsplash.com/photo-1528698827591-e19cef791f48?w=800&q=80',
        rating: 4.5,
        reviewCount: 220,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58027-tulear/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['italien', 'fruits de mer', 'pizza'],
          priceRange: 'MODERATE',
          avgMainCourse: 30000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: false,
          hasWifi: false,
        },
      },

      // =============================================
      // ANTSIRABE - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'Le Champierre',
        slug: 'le-champierre-antsirabe',
        description: "Considéré comme la meilleure table d'Antsirabe. Cuisine franco-malgache dans un cadre cosy. Réputé pour le confit de canard, foie gras, et spécialités des Hauts Plateaux : truite et écrevisses des rivières locales. Cheminée en saison fraîche. Atmosphère intime. Coup de Cœur Petit Futé.",
        shortDescription: 'Meilleur d\'Antsirabe, truite et confit, cheminée',
        address: 'Rue Rakoto Ratsimamanga',
        city: 'Antsirabe',
        district: 'Centre-ville',
        region: 'Vakinankaratra',
        latitude: -19.8667,
        longitude: 47.0333,
        phone: '+261 20 44 486 72',
        coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        rating: 4.5,
        reviewCount: 200,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57958-antsirabe/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'malgache', 'Hauts Plateaux'],
          priceRange: 'MODERATE',
          avgMainCourse: 35000,
          avgBeer: 8000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },

      // =============================================
      // FIANARANTSOA - RESTAURANTS (Petit Futé)
      // =============================================
      {
        type: 'RESTAURANT' as const,
        name: 'La Rizière',
        slug: 'la-riziere-fianarantsoa',
        description: "Restaurant dans la Haute-Ville atmosphérique de Fianarantsoa avec vue panoramique sur les rizières en terrasse. Cuisine franco-malgache avec spécialités des Hauts Plateaux : écrevisses, canard, et vins locaux des vignobles voisins (Lazan'i Betsileo, Clos Malaza). Le cadre seul vaut le détour. Coup de Cœur Petit Futé.",
        shortDescription: 'Vue rizières, cuisine Betsileo, vins locaux',
        address: 'Haute-Ville, près de la Cathédrale',
        city: 'Fianarantsoa',
        district: 'Haute-Ville',
        region: 'Haute Matsiatra',
        latitude: -21.4417,
        longitude: 47.0833,
        phone: '+261 34 07 500 20',
        coverImage: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800&q=80',
        rating: 4.5,
        reviewCount: 260,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v42578-fianarantsoa/c1165-restaurants/',
        sourceAttribution: 'Petit Futé Madagascar',
        restaurant: {
          category: 'RESTAURANT',
          cuisineTypes: ['français', 'malgache Betsileo', 'écrevisses'],
          priceRange: 'MODERATE',
          avgMainCourse: 30000,
          avgBeer: 7000,
          hasDelivery: false,
          hasTakeaway: false,
          hasReservation: true,
          hasWifi: true,
        },
      },

      // =============================================
      // HÔTELS - ANTANANARIVO (Petit Futé)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Hotel Carlton Madagascar',
        slug: 'hotel-carlton-antananarivo',
        description: "Le fleuron de l'hôtellerie de luxe à Antananarivo, surplombant le lac Anosy et ses jacarandas. Entièrement rénové aux standards internationaux 5 étoiles. Plusieurs restaurants dont un gastronomique français, spa complet, salles de conférence. Adresse de référence pour diplomates et voyageurs exigeants. Coup de Cœur Petit Futé.",
        shortDescription: 'Hôtel 5 étoiles, vue lac Anosy, référence de la capitale',
        address: 'Rue Pierre Stibbe, Anosy',
        city: 'Antananarivo',
        district: 'Anosy',
        region: 'Analamanga',
        latitude: -18.9200,
        longitude: 47.5220,
        phone: '+261 20 22 260 60',
        website: 'https://www.carltonmadagascar.com',
        coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        rating: 4.0,
        reviewCount: 800,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57953-antananarivo/c1165-hebergement/c1073-hotel/1155327-hotel-carlton.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 5,
          hotelType: 'hotel',
          amenities: ['wifi', 'pool', 'restaurant', 'spa', 'bar', 'parking', 'ac', 'conference', 'fitness', 'room_service', 'elevator', 'concierge', 'airport_shuttle'],
          checkInTime: '14:00',
          checkOutTime: '12:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Hotel Palissandre & Spa',
        slug: 'hotel-palissandre-spa-antananarivo',
        description: "Hôtel boutique raffiné au centre de Tana, design inspiré du bois de rose malgache (palissandre). Bar rooftop avec les plus belles vues coucher de soleil sur les collines. Spa parmi les meilleurs de la capitale, restaurant fusion franco-malgache créatif. Coup de Cœur Petit Futé pour son design et sa qualité constante.",
        shortDescription: 'Boutique design, rooftop bar, spa d\'exception',
        address: 'Rue Rainandriamampandry, Soarano',
        city: 'Antananarivo',
        district: 'Soarano',
        region: 'Analamanga',
        latitude: -18.9080,
        longitude: 47.5240,
        phone: '+261 20 22 605 60',
        website: 'https://www.hotel-palissandre.com',
        coverImage: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80',
        rating: 4.5,
        reviewCount: 450,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57953-antananarivo/c1165-hebergement/c1073-hotel/1467073-hotel-palissandre-spa.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'boutique',
          amenities: ['wifi', 'restaurant', 'spa', 'bar_rooftop', 'ac', 'room_service', 'fitness', 'elevator', 'terrasse'],
          checkInTime: '14:00',
          checkOutTime: '12:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Citizen Guesthouse',
        slug: 'citizen-guesthouse-antananarivo',
        description: "Maison d'hôtes design dans la Haute-Ville historique, résidence coloniale magnifiquement restaurée. Chaque chambre décorée avec art contemporain malgache. Jardin-terrasse paisible, petit-déjeuner exceptionnel avec confitures maison et café local. Accueil chaleureux et personnalisé. Coup de Cœur Petit Futé.",
        shortDescription: 'Maison d\'hôtes design, art malgache, Haute-Ville',
        address: 'Faravohitra, Haute-Ville',
        city: 'Antananarivo',
        district: 'Faravohitra',
        region: 'Analamanga',
        latitude: -18.9140,
        longitude: 47.5300,
        phone: '+261 34 14 000 14',
        website: 'https://www.citizen-guesthouse.com',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80',
        rating: 4.5,
        reviewCount: 300,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57953-antananarivo/c1165-hebergement/c838-chambres-d-hotes/',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 3,
          hotelType: 'chambre_hotes',
          amenities: ['wifi', 'restaurant_petit_dejeuner', 'parking', 'jardin', 'terrasse', 'ac_partiel', 'bibliotheque'],
          checkInTime: '13:00',
          checkOutTime: '11:00',
        },
      },

      // =============================================
      // HÔTELS - NOSY BE (Petit Futé)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Vanila Hotel & Spa',
        slug: 'vanila-hotel-spa-nosy-be',
        description: "Hôtel élégant alliant architecture traditionnelle malgache et confort moderne, dans des jardins tropicaux luxuriants menant à la plage. Spa signature utilisant vanille et ylang-ylang locaux. Restaurant servant d'excellents fruits de mer. Coup de Cœur Petit Futé pour le meilleur rapport qualité-prix haut de gamme de l'île.",
        shortDescription: 'Hôtel 4*, spa vanille et ylang-ylang, plage',
        address: 'Ambatoloaka',
        city: 'Nosy Be',
        district: 'Ambatoloaka',
        region: 'Diana',
        latitude: -13.3550,
        longitude: 48.2650,
        phone: '+261 20 86 920 88',
        website: 'https://www.vanila-hotel.com',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        rating: 4.5,
        reviewCount: 700,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58019-nosy-be/c1165-hebergement/c1073-hotel/1155342-vanila-hotel-spa.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'hotel',
          amenities: ['wifi', 'pool', 'restaurant', 'spa', 'bar', 'plage', 'ac', 'jardin', 'plongee', 'excursions', 'room_service'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Tsara Komba Lodge',
        slug: 'tsara-komba-lodge-nosy-komba',
        description: "Écolodge exclusif et intime perché sur une colline boisée surplombant les eaux turquoise entre Nosy Komba et Nosy Be. Seulement 8 lodges individuels en bois local et pierre. Accessible uniquement en bateau. Lémuriens noirs visitant le domaine quotidiennement. Snorkeling exceptionnel. 100% solaire, pas de TV par choix. Note parfaite TripAdvisor 5/5. Coup de Cœur Petit Futé.",
        shortDescription: 'Écolodge exclusif, 8 lodges, lémuriens, snorkeling',
        address: 'Nosy Komba',
        city: 'Nosy Be',
        district: 'Nosy Komba',
        region: 'Diana',
        latitude: -13.4500,
        longitude: 48.3500,
        phone: '+261 32 07 222 07',
        website: 'https://www.tsarakomba.com',
        coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
        rating: 5.0,
        reviewCount: 350,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58019-nosy-be/c1165-hebergement/c1081-lodge/1155345-tsara-komba-lodge.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'ecolodge',
          amenities: ['restaurant', 'bar', 'plage', 'snorkeling', 'kayak', 'massage', 'excursions', 'bibliotheque', 'solaire'],
          checkInTime: '12:00',
          checkOutTime: '10:00',
        },
      },

      // =============================================
      // HÔTELS - DIEGO SUAREZ (Petit Futé)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Le Domaine de Fontenay',
        slug: 'domaine-de-fontenay-diego-suarez',
        description: "Boutique hôtel de charme dans des jardins tropicaux luxuriants sur la route de Ramena. Bungalows individuels décorés avec goût en matériaux locaux. Piscine parmi frangipanier et arbres du voyageur. Restaurant gastronomique franco-malgache. Hôtes passionnés connaissant parfaitement le nord. Coup de Cœur Petit Futé.",
        shortDescription: 'Charme en jardin tropical, gastronomique, route de Ramena',
        address: 'Route de Ramena',
        city: 'Diego Suarez',
        district: 'Route de Ramena',
        region: 'Diana',
        latitude: -12.2600,
        longitude: 49.3100,
        phone: '+261 32 07 115 15',
        website: 'https://www.domainedefontenay.com',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        rating: 4.5,
        reviewCount: 300,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57985-diego-suarez-antsiranana/c1165-hebergement/c838-chambres-d-hotes/',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 3,
          hotelType: 'boutique',
          amenities: ['wifi', 'pool', 'restaurant', 'bar', 'parking', 'jardin', 'ac', 'excursions', 'bibliotheque', 'terrasse'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Nature Lodge',
        slug: 'nature-lodge-joffreville',
        description: "Écolodge à l'entrée du Parc National de la Montagne d'Ambre. Bungalows en bois sur pilotis dans la canopée de la forêt tropicale d'altitude. Vues sur la forêt et la baie de Diego les jours clairs. Randonnées guidées au départ du lodge. Climat frais (1200m d'altitude). Engagement écologique fort. Coup de Cœur Petit Futé.",
        shortDescription: 'Écolodge canopée, Montagne d\'Ambre, randonnées forêt',
        address: 'Joffreville, entrée Montagne d\'Ambre',
        city: 'Diego Suarez',
        district: 'Joffreville',
        region: 'Diana',
        latitude: -12.5300,
        longitude: 49.1700,
        phone: '+261 32 04 392 52',
        website: 'https://www.naturelodge-madagascar.com',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.5,
        reviewCount: 250,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57985-diego-suarez-antsiranana/c1165-hebergement/c1081-lodge/',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 3,
          hotelType: 'ecolodge',
          amenities: ['restaurant', 'bar', 'jardin', 'randonnees', 'wifi_limité', 'parking', 'terrasse_panoramique', 'eau_chaude', 'cheminee'],
          checkInTime: '14:00',
          checkOutTime: '10:00',
        },
      },

      // =============================================
      // HÔTELS - SAINTE-MARIE (Petit Futé)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Princesse Bora Lodge & Spa',
        slug: 'princesse-bora-sainte-marie',
        description: "L'adresse la plus luxueuse de Sainte-Marie et l'un des plus beaux boutique-hôtels de Madagascar. Villas individuelles avec piscine privée dans une cocoteraie menant à une plage de sable blanc. Spa de classe mondiale, restaurant gastronomique. Observation des baleines à bosse depuis la plage (juillet-septembre). Coup de Cœur Petit Futé année après année.",
        shortDescription: 'Lodge 5*, villas piscine privée, baleines, spa',
        address: 'Ambodifotatra',
        city: 'Sainte-Marie',
        district: 'Ambodifotatra',
        region: 'Analanjirofo',
        latitude: -16.8550,
        longitude: 49.9200,
        phone: '+261 20 57 912 18',
        website: 'https://www.princesse-bora.com',
        coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
        rating: 4.5,
        reviewCount: 500,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v58023-ile-sainte-marie/c1165-hebergement/c1081-lodge/1155349-princesse-bora-lodge-spa.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 5,
          hotelType: 'lodge',
          amenities: ['wifi', 'pool', 'pool_privee', 'restaurant', 'spa', 'bar', 'plage', 'ac', 'excursions_baleines', 'kayak', 'snorkeling', 'plongee', 'boutique'],
          checkInTime: '14:00',
          checkOutTime: '12:00',
        },
      },

      // =============================================
      // HÔTELS - SUD & PARCS NATIONAUX (Petit Futé)
      // =============================================
      {
        type: 'HOTEL' as const,
        name: 'Salary Bay',
        slug: 'salary-bay-southwest',
        description: "Écolodge exceptionnel sur une côte vierge du sud-ouest. Tentes de luxe et villas face à un lagon turquoise protégé par un récif. Entièrement solaire, engagé avec la communauté Vezo locale. Snorkeling et plongée sur un récif vierge de classe mondiale. TripAdvisor 5/5. Coup de Cœur Petit Futé.",
        shortDescription: 'Éco-luxe, lagon turquoise, récif vierge, 5/5 TripAdvisor',
        address: 'Salary, côte sud-ouest',
        city: 'Tuléar',
        district: 'Salary',
        region: 'Atsimo-Andrefana',
        latitude: -22.0800,
        longitude: 43.3200,
        phone: '+261 34 49 559 95',
        website: 'https://www.salary-bay.com',
        coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        rating: 5.0,
        reviewCount: 200,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/c1165-hebergement/c1081-lodge/madagascar/salary-bay.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'ecolodge',
          amenities: ['restaurant', 'bar', 'plage', 'snorkeling', 'plongee', 'kayak', 'kitesurf', 'excursions', 'solaire', 'wifi_satellite'],
          checkInTime: '12:00',
          checkOutTime: '10:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Isalo Rock Lodge',
        slug: 'isalo-rock-lodge-ranohira',
        description: "Lodge architecturalement remarquable construit dans le grès à l'entrée du Parc National d'Isalo. Piscine à débordement iconique fusionnant avec le canyon d'Isalo au coucher du soleil. Bungalows en pierre et verre avec vues panoramiques. Restaurant farm-to-table. L'un des plus beaux hôtels de Madagascar. Coup de Cœur Petit Futé.",
        shortDescription: 'Design lodge, piscine infinity iconique, Isalo',
        address: 'Ranohira, Parc National d\'Isalo',
        city: 'Ranohira',
        district: null,
        region: 'Ihorombe',
        latitude: -22.5500,
        longitude: 45.3600,
        phone: '+261 34 07 260 00',
        website: 'https://www.isalorocklodge.com',
        coverImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        rating: 4.5,
        reviewCount: 400,
        isFeatured: true,
        isPremium: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/c1165-hebergement/c1081-lodge/madagascar/isalo-rock-lodge.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'lodge',
          amenities: ['wifi', 'pool_infinity', 'restaurant', 'spa', 'bar', 'parking', 'jardin', 'terrasse', 'ac', 'excursions', 'cheminee', 'bibliotheque'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Le Relais de la Reine',
        slug: 'relais-de-la-reine-isalo',
        description: "Lodge raffiné dans un jardin botanique privé au pied du massif d'Isalo, sur la mythique RN7. Piscine sculptée dans la roche naturelle, bungalows en pierre et chaume. Restaurant avec potager du jardin. Équitation, VTT et randonnées dans les canyons. La référence historique près d'Isalo. Coup de Cœur Petit Futé.",
        shortDescription: 'Lodge jardin botanique, piscine rocheuse, équitation',
        address: 'RN7, Ranohira',
        city: 'Ranohira',
        district: null,
        region: 'Ihorombe',
        latitude: -22.5600,
        longitude: 45.3500,
        phone: '+261 20 22 081 35',
        website: 'https://www.relaisdelareine.com',
        coverImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        rating: 4.5,
        reviewCount: 500,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/c1165-hebergement/c1081-lodge/madagascar/relais-de-la-reine.html',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'lodge',
          amenities: ['wifi', 'pool', 'restaurant', 'spa', 'bar', 'parking', 'jardin_botanique', 'equitation', 'vtt', 'randonnees', 'ac', 'bibliotheque', 'boutique'],
          checkInTime: '14:00',
          checkOutTime: '11:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Mantadia Lodge',
        slug: 'mantadia-lodge-andasibe',
        description: "Écolodge haut de gamme nouvelle génération dans le corridor forestier d'Andasibe. Bungalows en bois sur pilotis immergés dans la forêt primaire. Grandes baies vitrées et terrasses privées sur la canopée. Randonnées guidées diurnes et nocturnes au Parc Mantadia. Restaurant raffiné dépassant les attentes pour un site aussi reculé. Coup de Cœur Petit Futé.",
        shortDescription: 'Écolodge premium en canopée, forêt primaire, lémuriens',
        address: 'Entrée Parc National Mantadia, Andasibe',
        city: 'Andasibe',
        district: null,
        region: 'Alaotra-Mangoro',
        latitude: -18.9200,
        longitude: 48.4300,
        phone: '+261 34 14 888 88',
        website: 'https://www.mantadialodge.com',
        coverImage: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
        rating: 4.5,
        reviewCount: 180,
        isFeatured: true,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/c1165-hebergement/c1081-lodge/madagascar/mantadia/',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 4,
          hotelType: 'ecolodge',
          amenities: ['restaurant', 'bar', 'wifi', 'randonnees', 'terrasse_privee', 'eau_chaude', 'observation_nature', 'eco_pratiques'],
          checkInTime: '14:00',
          checkOutTime: '10:00',
        },
      },
      {
        type: 'HOTEL' as const,
        name: 'Couleur Café',
        slug: 'couleur-cafe-antsirabe',
        description: "Maison d'hôtes délicieuse à Antsirabe tenue par un couple franco-malgache chaleureux. Chambres simples mais de bon goût, cuisine maison exceptionnelle avec produits des Hauts Plateaux. Conseils précieux sur la région Vakinankaratra. Les hôtes sont d'une gentillesse rare. Coup de Cœur Petit Futé, 9.1/10 Booking.",
        shortDescription: 'Maison d\'hôtes, cuisine maison exceptionnelle, accueil 9.1/10',
        address: 'Rue Rasoamanarivo',
        city: 'Antsirabe',
        district: 'Centre-ville',
        region: 'Vakinankaratra',
        latitude: -19.8700,
        longitude: 47.0350,
        phone: '+261 33 12 347 00',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80',
        rating: 4.5,
        reviewCount: 180,
        isFeatured: false,
        isActive: true,
        moderationStatus: 'pending_review',
        dataSource: 'csv_import',
        sourceUrl: 'https://www.petitfute.com/v57958-antsirabe/c1165-hebergement/c838-chambres-d-hotes/',
        sourceAttribution: 'Petit Futé Madagascar',
        hotel: {
          starRating: 2,
          hotelType: 'chambre_hotes',
          amenities: ['wifi', 'restaurant_maison', 'parking', 'jardin', 'excursions_conseil'],
          checkInTime: '13:00',
          checkOutTime: '10:00',
        },
      },
    ];

    // Insert each establishment, skipping duplicates
    for (const est of establishments) {
      const existing = await prisma.establishment.findFirst({
        where: { slug: est.slug },
      });

      if (existing) {
        created.skipped++;
        continue;
      }

      const { restaurant, hotel, ...establishmentData } = est as any;

      const data: any = {
        ...establishmentData,
        metaTitle: `${est.name} - ${est.city} | Mada Spot Bons Plans`,
        metaDescription: (est as any).shortDescription || est.description.substring(0, 155),
      };

      if (est.type === 'RESTAURANT' && restaurant) {
        data.restaurant = {
          create: {
            category: restaurant.category,
            cuisineTypes: JSON.stringify(restaurant.cuisineTypes || []),
            priceRange: restaurant.priceRange,
            avgMainCourse: restaurant.avgMainCourse || null,
            avgBeer: restaurant.avgBeer || null,
            hasDelivery: restaurant.hasDelivery || false,
            hasTakeaway: restaurant.hasTakeaway || false,
            hasReservation: restaurant.hasReservation || false,
            hasWifi: restaurant.hasWifi || false,
            openingHours: restaurant.openingHours ? JSON.stringify(restaurant.openingHours) : null,
          },
        };
        created.restaurants++;
      } else if (est.type === 'HOTEL' && hotel) {
        data.hotel = {
          create: {
            starRating: hotel.starRating || 3,
            hotelType: hotel.hotelType || 'hotel',
            amenities: JSON.stringify(hotel.amenities || []),
            checkInTime: hotel.checkInTime || '14:00',
            checkOutTime: hotel.checkOutTime || '11:00',
          },
        };
        created.hotels++;
      }

      await prisma.establishment.create({ data });
    }

    return NextResponse.json({
      success: true,
      message: `Seed Petit Futé terminé ! ${created.restaurants} restaurants, ${created.hotels} hôtels importés. ${created.skipped} doublons ignorés.`,
      created,
      source: 'Données sourcées depuis Petit Futé Madagascar, TripAdvisor et Booking.com. Tous les établissements sont "Coup de Cœur" ou très bien notés.',
      note: 'Tous les établissements sont en statut "pending_review" pour modération admin.',
    });
  } catch (error: unknown) {
    logger.error('Seed Petit Futé error:', error);
    const message = error instanceof Error ? error.message : 'Erreur inconnue';
    return NextResponse.json(
      { error: message },
      { status: 500 }
    );
  }
}
